let recipes = [], plan = [], shopping = [], pendingImport = [];
let currentWeekStart = mondayISO(new Date()), viewedPlanItemId = null;
let selectionContext = null, viewedRecipeId = null, previousView = 'recipes', shoppingGroupMode = 'store';
const viewScrollPositions={home:0,recipes:0,planner:0,shopping:0,recipeView:0,restaurants:0,restaurantView:0,producers:0,producerView:0,herbs:0,herbView:0,produce:0,produceView:0};
const days = ["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"];
const slots = ["Matin","Midi","Soir"];
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const norm = s => (s || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const recipeStore='hg-recipes-v271', planStore='hg-plan-v271', shoppingStore='hg-shopping-v271', slotStore='hg-day-slots-v271';
const shoppingAssignmentStore='hg-shopping-assignments-v251';
const APP_VERSION='2.9.4';
const mealTransferStore='hg-meal-transfers-v272', weekStore='hg-current-week-v272';
const weekSlotStore='hg-week-slots-v28', aisleOrderStore='hg-aisle-order-v28';
const mealNoteStore='hg-meal-notes-v294', shoppingStoreMemory='hg-shopping-stores-v294';
const BACKUP_META_KEY='hg-backup-meta-v26';
const EMERGENCY_BACKUP_KEY='hg-emergency-before-import-v26';
const CHANGE_COUNTER_KEY='hg-changes-since-backup-v26';
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;

function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function mondayISO(value){const d=new Date(value);d.setHours(12,0,0,0);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return isoDate(d)}
function addDaysISO(iso,n){const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+n);return isoDate(d)}
function dateLabel(iso){return new Intl.DateTimeFormat('fr-CH',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${iso}T12:00:00`))}
function weekLabel(start){const end=addDaysISO(start,6);return `${new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'2-digit'}).format(new Date(`${start}T12:00:00`))} – ${new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${end}T12:00:00`))}`}
function mealKey(date,slot){return `${date}|${slot}`}
function sameMeal(a,b){return a.date===b.date&&a.slot===b.slot}
function mealItems(date,slot){return plan.filter(x=>x.date===date&&x.slot===slot)}
function mealPeople(date,slot){const value=Number(mealItems(date,slot)[0]?.people);return value>=1&&value<=10?value:''}
function setMealPeople(date,slot,value){const n=Number(value),p=n>=1&&n<=10?n:null;mealItems(date,slot).forEach(x=>x.people=p);savePlanData();renderPlan();}
function savePlanData(){localStorage.setItem(planStore,JSON.stringify({version:3,weekStart:currentWeekStart,time:$('#planTime')?.value||'',items:plan.map(x=>({uid:x.uid||uid(),date:x.date,slot:x.slot,id:x.recipe.id,people:(Number(x.people)>=1&&Number(x.people)<=10?Number(x.people):null),role:x.role||'',notes:x.notes||'',preparePreviousDay:Boolean(x.preparePreviousDay)}))}));markDirty();}
function mealTransfers(){try{return JSON.parse(localStorage.getItem(mealTransferStore)||'{}')}catch{return{}}}
function saveMealTransfers(x){localStorage.setItem(mealTransferStore,JSON.stringify(x));markDirty()}
async function init(){
  currentWeekStart=localStorage.getItem(weekStore)||mondayISO(new Date());
  await autoLoadSharedBackup();
  migrateLegacyWeekSlots();
  renderDaySlotChoices();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js?v=2940', {updateViaCache:'none'});
  const stored=JSON.parse(localStorage.getItem(recipeStore)||'null');
  if(stored) recipes=stored; else recipes=await fetch(`recipes.json?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());
  recipes=recipes.map(normalizeRecipe);
  fillCategories(); renderRecipes(); loadSaved(); await initRestaurants(); await initProducers(); await initHerbs(); await initProduce(); applyReadonlyMode(); checkForUpdate();
}
function saveRecipes(){localStorage.setItem(recipeStore,JSON.stringify(recipes));registerProtectedChange();markDirty();}
function activeViewId(){return document.querySelector('.view.active')?.id||'home'}
function rememberScroll(view=activeViewId()){viewScrollPositions[view]=scrollY}
function restoreScroll(view){requestAnimationFrame(()=>scrollTo(0,viewScrollPositions[view]||0))}
function keepScroll(action,view=activeViewId()){const y=scrollY;action();requestAnimationFrame(()=>scrollTo(0,y));viewScrollPositions[view]=y}
function switchView(id,{top=false}={}){const from=activeViewId();if(from!==id)rememberScroll(from);$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(top)viewScrollPositions[id]=0;restoreScroll(id);updateWakeLock(id);}
let wakeLock=null;
async function updateWakeLock(view=activeViewId()){
  const shouldStayAwake=['shopping','recipeView'].includes(view)&&document.visibilityState==='visible';
  try{
    if(shouldStayAwake&&!wakeLock&&'wakeLock' in navigator){wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}
    else if(!shouldStayAwake&&wakeLock){await wakeLock.release();wakeLock=null}
  }catch(e){console.warn('Maintien de l’écran indisponible',e)}
}
document.addEventListener('visibilitychange',()=>updateWakeLock());
$$('nav button').forEach(b=>b.onclick=()=>{selectionContext=null;updateSelectionBar();switchView(b.dataset.view)});
$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
function slug(s){return (norm(s).replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'recette')+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,5)}
function normalizeRecipe(r){return {id:String(r.id||r.uid||slug(r.title||r.name||'recette')),title:r.title||r.name||'Recette sans titre',category:r.category||'Importée',time:Number(r.time)||0,servings:Number(r.servings)||4,ingredients:Array.isArray(r.ingredients)?r.ingredients:[],steps:Array.isArray(r.steps)?r.steps:[],avecViande:!!r.avecViande,temperature:r.temperature||'les-deux',tags:Array.isArray(r.tags)?r.tags:[],source:r.source||'',notes:r.notes||'',paprikaUid:r.paprikaUid||r.uid||''};}
function fillCategories(){const cats=[...new Set(recipes.map(r=>r.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));$('#category').innerHTML='<option value="">Toutes catégories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const form=$('#recipeCategory'),current=form?.value||'';if(form){form.innerHTML='<option value="">Choisir…</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')+'<option value="__other__">Autre…</option>';if(cats.includes(current))form.value=current;}}
function recipeCard(r){const choose=selectionContext?`<button class="primary" data-choose="${esc(r.id)}">Choisir pour ${esc(dateLabel(selectionContext.date))} ${esc(selectionContext.slot.toLowerCase())}</button>`:'';return `<article class="recipe" data-recipe-open="${esc(r.id)}"><div class="recipe-head"><div class="meta">${esc(r.category)} · ${r.time||'?'} min · ${r.servings} pers.</div><h3>${esc(r.title)}</h3><div class="badges">${(r.tags||[]).slice(0,5).map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="recipe-actions">${choose}<button data-edit="${esc(r.id)}">Modifier</button><button data-print-recipe="${esc(r.id)}">Imprimer</button></div></article>`;}
function renderRecipes(){const q=norm($('#search').value),cat=$('#category').value,max=+$('#maxTime').value||999;const found=recipes.filter(r=>(!cat||r.category===cat)&&(r.time||0)<=max&&(!q||norm(JSON.stringify(r)).includes(q))).sort((a,b)=>a.title.localeCompare(b.title,'fr',{sensitivity:'base'}));$('#recipeCount').textContent=`${found.length} recette${found.length>1?'s':''}`;$('#recipeList').innerHTML=found.map(recipeCard).join('')||'<p>Aucune recette trouvée.</p>';bindRecipeCards($('#recipeList'));}
function bindRecipeCards(root=document){root.querySelectorAll('[data-recipe-open]').forEach(card=>card.onclick=e=>{if(e.target.closest('button'))return;showRecipe(card.dataset.recipeOpen,'recipes')});root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openRecipe(b.dataset.edit)});root.querySelectorAll('[data-print-recipe]').forEach(b=>b.onclick=e=>{e.stopPropagation();printRecipe(recipes.find(r=>r.id===b.dataset.printRecipe))});root.querySelectorAll('[data-choose]').forEach(b=>b.onclick=e=>{e.stopPropagation();chooseRecipeForPlan(b.dataset.choose)});}
$('#search').oninput=renderRecipes;$('#category').onchange=renderRecipes;$('#maxTime').onchange=renderRecipes;
$('#surpriseBtn').onclick=()=>{if(!recipes.length)return;const r=recipes[Math.floor(Math.random()*recipes.length)];$('#surpriseCard').innerHTML=recipeCard(r);bindRecipeCards($('#surpriseCard'));};
function updateSelectionBar(){const active=!!selectionContext;$('#recipeReturnBar').classList.toggle('hidden',!active);$('#selectionHint').textContent=active?`Choix pour ${dateLabel(selectionContext.date)} ${selectionContext.slot.toLowerCase()}`:'';renderRecipes();}
$('#returnPlanner').onclick=()=>{selectionContext=null;updateSelectionBar();switchView('planner')};
function startRecipeChoice(index,date=null,slot=null){
  const existing=Number.isInteger(index)&&plan[index];
  selectionContext={index:existing?index:null,date:existing?existing.date:date,slot:existing?existing.slot:slot};
  rememberScroll('planner');updateSelectionBar();switchView('recipes',{top:true});$('#search').focus();
}
function chooseRecipeForPlan(id){if(!selectionContext)return;const r=recipes.find(x=>x.id===id);if(!r)return;const ctx={...selectionContext};if(Number.isInteger(ctx.index)&&plan[ctx.index])plan[ctx.index].recipe=r;else plan.push({uid:uid(),date:ctx.date,slot:ctx.slot,recipe:r,people:mealPeople(ctx.date,ctx.slot)||null,role:''});selectionContext=null;savePlanData();renderPlan();updateSelectionBar();switchView('planner');}
function recipeSourceMarkup(source){if(!source)return '';try{const url=new URL(source);const host=url.hostname.replace(/^www\./,'');return `<p class="recipe-source muted">Source : <a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(host)}</a></p>`;}catch{return `<p class="recipe-source muted">Source : ${esc(source)}</p>`;}}
function showRecipe(id,from=''){const r=recipes.find(x=>x.id===id);if(!r)return;if(from){rememberScroll(from);previousView=from}else if(!previousView)previousView='recipes';viewedRecipeId=id;$('#recipeViewContent').innerHTML=`<div class="recipe-title"><div class="meta">${esc(r.category)} · ${r.time||'?'} min · ${r.servings} pers. · ${esc(r.temperature)}</div><h2>${esc(r.title)}</h2>${recipeSourceMarkup(r.source)}</div><div class="recipe-columns"><section><h3>Ingrédients</h3><ul>${scaledIngredients(r,r.servings).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><h3>Préparation</h3><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${r.notes?`<h3>Notes</h3><p>${esc(r.notes).replace(/\n/g,'<br>')}</p>`:''}</section></div>`;switchView('recipeView');}
$('#backFromRecipe').onclick=()=>switchView(previousView);$('#editViewedRecipe').onclick=()=>openRecipe(viewedRecipeId);$('#printViewedRecipe').onclick=()=>printRecipe(recipes.find(r=>r.id===viewedRecipeId));

function openRecipe(id){const r=recipes.find(x=>x.id===id);$('#recipeDialogTitle').textContent=r?'Modifier la recette':'Nouvelle recette';$('#recipeId').value=r?.id||'';$('#recipeTitle').value=r?.title||'';$('#recipeCategory').value=r?.category||'';$('#recipeTime').value=r?.time||30;$('#recipeServings').value=r?.servings||4;$('#recipeTemperature').value=r?.temperature||'chaud';$('#recipeMeat').checked=!!r?.avecViande;$('#recipeIngredients').value=(r?.ingredients||[]).map(i=>i.join(' / ')).join('\n');$('#recipeSteps').value=(r?.steps||[]).join('\n');$('#recipeTags').value=(r?.tags||[]).join(', ');$('#deleteRecipe').classList.toggle('hidden',!r);$('#duplicateRecipe').classList.toggle('hidden',!r);$('#recipeDialog').showModal();}
$('#newRecipe').onclick=()=>openRecipe();$('#closeRecipe').onclick=()=>$('#recipeDialog').close();
function parseNumber(v){const s=String(v??'').trim().replace(',','.').replace('½','.5').replace('¼','.25').replace('¾','.75');if(/^\d+\s+\d+\/\d+$/.test(s)){const [a,f]=s.split(/\s+/),[n,d]=f.split('/').map(Number);return Number(a)+n/d;}if(/^\d+\/\d+$/.test(s)){const [n,d]=s.split('/').map(Number);return n/d;}const n=Number(s);return Number.isFinite(n)?n:v;}
function formRecipe(newId=false){const ingredients=$('#recipeIngredients').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [n,q='',u='']=line.split('/').map(x=>x.trim());return[n,parseNumber(q),u]});const existing=recipes.find(x=>x.id===$('#recipeId').value);return normalizeRecipe({id:newId||$('#recipeId').value||slug($('#recipeTitle').value),title:$('#recipeTitle').value.trim(),category:$('#recipeCategory').value.trim(),time:+$('#recipeTime').value,servings:+$('#recipeServings').value,temperature:$('#recipeTemperature').value,avecViande:$('#recipeMeat').checked,ingredients,steps:$('#recipeSteps').value.split('\n').map(x=>x.trim()).filter(Boolean),tags:$('#recipeTags').value.split(',').map(x=>x.trim()).filter(Boolean),source:existing?.source||'',notes:existing?.notes||'',paprikaUid:existing?.paprikaUid||''});}
$('#recipeForm').onsubmit=e=>{e.preventDefault();const r=formRecipe();const i=recipes.findIndex(x=>x.id===r.id);if(i>=0)recipes[i]=r;else recipes.unshift(r);plan.forEach(item=>{if(item.recipe?.id===r.id)item.recipe=r});saveRecipes();savePlanData();fillCategories();keepScroll(renderRecipes,'recipes');renderPlan();invalidateShopping('Une recette a été modifiée : les affichages du planning sont à jour. Retransfère le repas dans les courses si les ingrédients ont changé.');$('#recipeDialog').close();if(viewedRecipeId===r.id){const pi=plan.findIndex(x=>x.uid===viewedPlanItemId);if(previousView==='planner'&&pi>=0)showPlanRecipe(pi);else showRecipe(r.id)}};
$('#deleteRecipe').onclick=()=>{const id=$('#recipeId').value;if(id&&confirm('Supprimer définitivement cette recette ?')){recipes=recipes.filter(r=>r.id!==id);plan=plan.filter(x=>x.recipe.id!==id);saveRecipes();fillCategories();keepScroll(renderRecipes,'recipes');renderPlan();invalidateShopping('Une recette du planning a été supprimée.');$('#recipeDialog').close();switchView('recipes')}};
$('#duplicateRecipe').onclick=()=>{const r=formRecipe(slug($('#recipeTitle').value));r.title+=' (copie)';recipes.unshift(r);saveRecipes();fillCategories();keepScroll(renderRecipes,'recipes');$('#recipeDialog').close();};

function defaultDaySlots(){return Object.fromEntries(days.map((_,i)=>[i,Object.fromEntries(slots.map(s=>[s,false]))]))}
function readWeekSlots(){try{return JSON.parse(localStorage.getItem(weekSlotStore)||'{}')||{}}catch{return{}}}
function migrateLegacyWeekSlots(){
  const map=readWeekSlots();
  if(Object.keys(map).length)return;
  try{const legacy=JSON.parse(localStorage.getItem(slotStore)||'null');if(legacy)map[currentWeekStart]={...defaultDaySlots(),...legacy}}catch{}
  localStorage.setItem(weekSlotStore,JSON.stringify(map));
}
function readDaySlots(){const map=readWeekSlots();return map[currentWeekStart]?{...defaultDaySlots(),...map[currentWeekStart]}:defaultDaySlots()}
function renderDaySlotChoices(){const state=readDaySlots();$('#daySlotChoices').innerHTML=days.map((day,i)=>`<div class="day-slot-row"><strong>${day}</strong>${slots.map(slot=>`<label class="mini-slot ${state[i]?.[slot]?'selected':''}"><input type="checkbox" data-day-slot="${i}" data-slot="${slot}" ${state[i]?.[slot]?'checked':''}><span>${slot}</span></label>`).join('')}</div>`).join('');$$('[data-day-slot]').forEach(c=>c.onchange=()=>{c.parentElement.classList.toggle('selected',c.checked);saveDaySlots();updateSlotStatus();renderPlan()});updateSlotStatus();}
function saveDaySlots(){const state=defaultDaySlots();$$('[data-day-slot]').forEach(c=>state[c.dataset.daySlot][c.dataset.slot]=c.checked);const map=readWeekSlots();map[currentWeekStart]=state;localStorage.setItem(weekSlotStore,JSON.stringify(map));markDirty();}
function selectedDaySlots(){return $$('[data-day-slot]:checked').map(c=>({date:addDaysISO(currentWeekStart,+c.dataset.daySlot),dayIndex:+c.dataset.daySlot,slot:c.dataset.slot}))}
function updateSlotStatus(){const n=selectedDaySlots().length;$('#selectedSlotsStatus').textContent=`${n} repas`;}
function choices(exclude=[]){const max=+$('#planTime').value||999;let pool=recipes.filter(r=>(!r.time||r.time<=max)&&!exclude.includes(r.id));return pool.length?pool:recipes.filter(r=>!exclude.includes(r.id));}
function pickRandom(a){return a[Math.floor(Math.random()*a.length)]}
$('#generatePlan').onclick=()=>{const targets=selectedDaySlots();if(!targets.length)return alert('Choisis au moins un repas.');const used=[];targets.forEach(t=>{if(mealItems(t.date,t.slot).length)return;let pool=choices(used);if(!pool.length)pool=choices([]);const recipe=pickRandom(pool);if(recipe){used.push(recipe.id);plan.push({uid:uid(),date:t.date,slot:t.slot,recipe,people:null,role:''})}});savePlanData();renderPlan();};
function scaledIngredientRows(r,people=r.servings,overrides={}){const f=(Number(people)||r.servings)/(r.servings||4);return r.ingredients.map(([n,q,u],i)=>{const ov=overrides[i];const amount=ov!==undefined?ov:(typeof q==='number'?Math.round(q*f*100)/100:q||'');return{name:n,qty:amount,unit:u||'',text:`${n} : ${amount??''} ${u||''}`.trim()}})}
function scaledIngredients(r,people=null,overrides={}){const p=people||Number($('#people')?.value)||r.servings;return scaledIngredientRows(r,p,overrides).map(x=>x.text)}
function mealNotes(){try{return JSON.parse(localStorage.getItem(mealNoteStore)||'{}')||{}}catch{return{}}}
function mealNote(date,slot){return mealNotes()[mealKey(date,slot)]||''}
function setMealNote(date,slot,value){const all=mealNotes(),key=mealKey(date,slot),v=String(value||'').trim();if(v)all[key]=v;else delete all[key];localStorage.setItem(mealNoteStore,JSON.stringify(all));markDirty()}
let movingPlanIndex=null;
function movePlanItem(index){const item=plan[index];if(!item)return;movingPlanIndex=index;$('#movePlanDate').value=item.date;$('#movePlanSlot').value=item.slot;$('#movePlanDialog').showModal();}
$('#closeMovePlan').onclick=$('#cancelMovePlan').onclick=()=>{$('#movePlanDialog').close();movingPlanIndex=null};
$('#movePlanForm').onsubmit=e=>{e.preventDefault();const item=plan[movingPlanIndex];if(!item)return;const date=$('#movePlanDate').value,slot=$('#movePlanSlot').value;if(!date||!slots.includes(slot))return;item.date=date;item.slot=slot;savePlanData();renderPlan();$('#movePlanDialog').close();movingPlanIndex=null;};
function removePlanItem(index){const item=plan[index];if(!item)return;if(confirm(`Retirer « ${item.recipe.title} » du planning ?`)){plan.splice(index,1);savePlanData();keepScroll(renderPlan,'planner')}}
function setPlanRole(index){const item=plan[index];if(!item)return;const role=prompt('Rôle dans le repas (entrée, plat, accompagnement, dessert, sauce, boisson…)',item.role||'');if(role===null)return;item.role=role.trim();savePlanData();renderPlan();}
function togglePreparePreviousDay(index){const item=plan[index];if(!item)return;item.preparePreviousDay=!item.preparePreviousDay;savePlanData();renderPlan();}
function preparationsForDate(date){return plan.filter(x=>x.preparePreviousDay&&addDaysISO(x.date,-1)===date)}
function showPlanRecipe(index){const m=plan[index];if(!m)return;viewedPlanItemId=m.uid;rememberScroll('planner');viewedRecipeId=m.recipe.id;previousView='planner';const rows=scaledIngredientRows(m.recipe,m.people,m.qtyOverrides||{});$('#recipeViewContent').innerHTML=`<div class="recipe-title"><div class="meta">${esc(m.recipe.category)} · ${m.recipe.time||'?'} min${m.people?` · adapté à ${m.people} pers.`:' · portions originales'} · ${esc(dateLabel(m.date))} ${esc(m.slot.toLowerCase())}</div><h2>${esc(m.recipe.title)}</h2>${recipeSourceMarkup(m.recipe.source)}</div><div class="notice subtle">Cette adaptation appartient uniquement à ce repas. La recette originale reste inchangée.</div><div class="recipe-columns"><section><h3>Ingrédients</h3><ul>${rows.map(x=>`<li>${esc(x.text)}</li>`).join('')}</ul></section><section><h3>Préparation</h3><ol>${m.recipe.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${m.notes?`<h3>Notes du repas</h3><p>${esc(m.notes).replace(/\n/g,'<br>')}</p>`:''}</section></div>`;switchView('recipeView');}
function renderPlan(){
  $('#weekLabel').textContent=weekLabel(currentWeekStart);
  const weekDates=days.map((_,i)=>addDaysISO(currentWeekStart,i));
  const selected=selectedDaySlots();
  const activeDates=weekDates.filter(date=>selected.some(x=>x.date===date)||plan.some(x=>x.date===date)||preparationsForDate(date).length);
  if(!activeDates.length){$('#weekPlan').innerHTML='<p class="muted">Aucun repas sélectionné pour cette semaine.</p>';return}
  $('#weekPlan').innerHTML=activeDates.map(date=>{
    const d=new Date(`${date}T12:00:00`);
    const prep=preparationsForDate(date);
    const visibleSlots=[...new Set([...selected.filter(x=>x.date===date).map(x=>x.slot),...plan.filter(x=>x.date===date).map(x=>x.slot)])].sort((a,b)=>slots.indexOf(a)-slots.indexOf(b));
    const prepMarkup=prep.length?`<div class="notice subtle preparation-notice"><strong>À préparer aujourd’hui pour demain</strong>${prep.map(x=>`<div>• ${esc(x.recipe.title)} — ${esc(x.slot.toLowerCase())}${x.people?` · ${x.people} pers.`:''}</div>`).join('')}</div>`:'';
    return `<article class="day"><h3>${esc(dateLabel(date))}</h3>${prepMarkup}${visibleSlots.map(slot=>{
      const matches=mealItems(date,slot),p=mealPeople(date,slot);
      return `<section class="meal-group"><div class="meal-group-head"><strong>${slot}</strong><label class="meal-people">Personnes <select data-meal-people="${date}|${slot}"><option value="">—</option>${Array.from({length:10},(_,i)=>i+1).map(n=>`<option value="${n}" ${p===n?'selected':''}>${n}</option>`).join('')}</select></label><button data-add-plan="${date}|${slot}">+ Ajouter une recette</button><button class="primary" data-transfer-meal="${date}|${slot}" ${matches.length?'':'disabled'}>Transférer dans les courses</button></div><label class="meal-free-note">Ajout / remarque <input data-meal-note="${date}|${slot}" value="${esc(mealNote(date,slot))}" placeholder="Ex. salade, spätzli, raviolis al brodo…"></label>${matches.length?matches.map(m=>{
        const i=plan.indexOf(m),r=m.recipe;
        return `<div class="meal meal-line"><button class="meal-title-link" data-show-plan="${i}"><span>${m.role?`<b>${esc(m.role)}</b> · `:''}${esc(r.title)}</span><small>${r.time||'?'} min · ${esc(r.category)}${m.people?` · adapté à ${m.people} pers.`:' · personnes à définir'}${m.preparePreviousDay?' · à préparer la veille':''}</small></button><div class="meal-actions"><button data-prepare-plan="${i}" class="${m.preparePreviousDay?'primary':''}">${m.preparePreviousDay?'✓ Veille':'À préparer la veille'}</button><button data-role-plan="${i}">Rôle</button><button data-change-plan="${i}">Changer</button><button data-move-plan="${i}">Déplacer</button><button data-remove-plan="${i}" class="danger-soft">Retirer</button></div></div>`
      }).join(''):`<div class="meal meal-empty"><span class="meta">Aucune recette choisie</span></div>`}</section>`
    }).join('')}</article>`
  }).join('');
  $$('[data-add-plan]').forEach(b=>b.onclick=()=>{const [date,slot]=b.dataset.addPlan.split('|');startRecipeChoice(null,date,slot)});
  $$('[data-change-plan]').forEach(b=>b.onclick=()=>startRecipeChoice(+b.dataset.changePlan));
  $$('[data-show-plan]').forEach(b=>b.onclick=()=>showPlanRecipe(+b.dataset.showPlan));
  $$('[data-prepare-plan]').forEach(b=>b.onclick=()=>togglePreparePreviousDay(+b.dataset.preparePlan));
  $$('[data-move-plan]').forEach(b=>b.onclick=()=>movePlanItem(+b.dataset.movePlan));
  $$('[data-remove-plan]').forEach(b=>b.onclick=()=>removePlanItem(+b.dataset.removePlan));
  $$('[data-role-plan]').forEach(b=>b.onclick=()=>setPlanRole(+b.dataset.rolePlan));
  $$('[data-meal-people]').forEach(i=>i.onchange=()=>{const [date,slot]=i.dataset.mealPeople.split('|');setMealPeople(date,slot,i.value)});
  $$('[data-meal-note]').forEach(i=>i.onchange=()=>{const [date,slot]=i.dataset.mealNote.split('|');setMealNote(date,slot,i.value)});
  $$('[data-transfer-meal]').forEach(b=>b.onclick=()=>{const [date,slot]=b.dataset.transferMeal.split('|');transferMealToShopping(date,slot)});
}
$('#prevWeek').onclick=()=>{currentWeekStart=addDaysISO(currentWeekStart,-7);localStorage.setItem(weekStore,currentWeekStart);renderDaySlotChoices();renderPlan()};
$('#nextWeek').onclick=()=>{currentWeekStart=addDaysISO(currentWeekStart,7);localStorage.setItem(weekStore,currentWeekStart);renderDaySlotChoices();renderPlan()};
$('#currentWeek').onclick=()=>{currentWeekStart=mondayISO(new Date());localStorage.setItem(weekStore,currentWeekStart);renderDaySlotChoices();renderPlan()};
$('#clearPlan').onclick=()=>{if(confirm(`Vider uniquement le planning de la semaine ${weekLabel(currentWeekStart)} et remettre ses sélections à zéro ?`)){const dates=new Set(days.map((_,i)=>addDaysISO(currentWeekStart,i)));plan=plan.filter(x=>!dates.has(x.date));$$('[data-day-slot]').forEach(c=>{c.checked=false;c.parentElement.classList.remove('selected')});saveDaySlots();$('#planTime').value='';savePlanData();updateSlotStatus();renderPlan()}};
$('#savePlan').onclick=()=>{savePlanData();$('#planFreshness').textContent='Calendrier culinaire enregistré sur cet appareil.';$('#planFreshness').classList.remove('hidden')};
function invalidateShopping(message){$('#planFreshness').textContent=message;$('#planFreshness').classList.remove('hidden')}
function shoppingAssignments(){try{return JSON.parse(localStorage.getItem(shoppingAssignmentStore)||'{}')}catch{return{}}}
function normalizeShoppingItem(x={}){const pref=shoppingAssignments()[norm(x.name||x.ingredient)]||{};return{id:x.id||uid(),name:x.name||x.ingredient||'',qty:x.qty??x.quantite??0,text:x.text||'',unit:x.unit||x.unite||'',store:x.store||x.magasin||pref.store||'',aisle:x.aisle||x.rayon||pref.aisle||'',checked:Boolean(x.checked??x.coche),manual:Boolean(x.manual),origins:Array.isArray(x.origins)?x.origins:Array.isArray(x.sources)?x.sources:Array.isArray(x.origine)?x.origine:[]}}
function rememberShoppingAssignments(){const saved=shoppingAssignments();shopping.forEach(x=>{if(x.name&&(x.store||x.aisle))saved[norm(x.name)]={store:x.store||'',aisle:x.aisle||''}});localStorage.setItem(shoppingAssignmentStore,JSON.stringify(saved))}
function saveShopping(){shopping=shopping.map(normalizeShoppingItem);localStorage.setItem(shoppingStore,JSON.stringify(shopping));rememberShoppingAssignments();markDirty()}
function transferMealToShopping(date,slot){const items=mealItems(date,slot);if(!items.length)return alert('Ajoute d’abord une recette à ce repas.');if(!mealPeople(date,slot))return alert('Indique d’abord le nombre de personnes pour ce repas.');const key=mealKey(date,slot),transfers=mealTransfers(),previous=transfers[key]||[];
  previous.forEach(old=>{const x=shopping.find(s=>norm(s.name)===norm(old.name)&&norm(s.unit)===norm(old.unit));if(x&&typeof x.qty==='number')x.qty=Math.max(0,Math.round((x.qty-Number(old.qty||0))*100)/100)});
  shopping=shopping.filter(x=>x.manual||Number(x.qty)>0||x.text);
  const added=[];const prefs=shoppingAssignments();
  items.forEach(m=>scaledIngredientRows(m.recipe,m.people,m.qtyOverrides||{}).forEach(row=>{const q=Number(row.qty);if(!Number.isFinite(q)||q===0)return;let x=shopping.find(s=>!s.manual&&norm(s.name)===norm(row.name)&&norm(s.unit)===norm(row.unit));const pref=prefs[norm(row.name)]||{};if(!x){x=normalizeShoppingItem({name:row.name,qty:0,unit:row.unit,store:pref.store||'',aisle:pref.aisle||'',origins:[]});shopping.push(x)}x.qty=Math.round((Number(x.qty||0)+q)*100)/100;const origin=`${dateLabel(date)} ${slot} · ${m.recipe.title}`;if(!x.origins.includes(origin))x.origins.push(origin);added.push({name:row.name,unit:row.unit,qty:q})}));
  transfers[key]=added;saveMealTransfers(transfers);saveShopping();renderShopping();$('#planFreshness').textContent=`${dateLabel(date)} ${slot.toLowerCase()} transféré dans la liste des courses.`;$('#planFreshness').classList.remove('hidden');switchView('shopping');
}
function aisleOrders(){try{return JSON.parse(localStorage.getItem(aisleOrderStore)||'{}')||{}}catch{return{}}}
function saveAisleOrders(value){localStorage.setItem(aisleOrderStore,JSON.stringify(value));markDirty()}
function aislesForStore(store){
  const existing=[...new Set(shopping.filter(x=>(x.store||'')===store).map(x=>x.aisle||'Rayon à définir'))];
  const saved=aisleOrders()[store]||[];
  return [...saved.filter(x=>existing.includes(x)),...existing.filter(x=>!saved.includes(x)).sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}))];
}
function aisleRank(store,aisle){const list=aislesForStore(store);const i=list.indexOf(aisle||'Rayon à définir');return i<0?9999:i}
function renderAisleOrderEditor(){
  const stores=[...new Set(shopping.map(x=>x.store).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));
  const select=$('#aisleOrderStore');select.innerHTML=stores.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')||'<option value="">Aucun magasin</option>';
  const render=()=>{const store=select.value,list=store?aislesForStore(store):[];$('#aisleOrderList').innerHTML=list.map((name,i)=>`<div class="aisle-order-row"><span>${esc(name)}</span><div><button type="button" data-aisle-up="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-aisle-down="${i}" ${i===list.length-1?'disabled':''}>↓</button></div></div>`).join('')||'<p class="muted">Aucun rayon enregistré pour ce magasin.</p>';$$('[data-aisle-up]').forEach(b=>b.onclick=()=>moveAisle(store,+b.dataset.aisleUp,-1));$$('[data-aisle-down]').forEach(b=>b.onclick=()=>moveAisle(store,+b.dataset.aisleDown,1));};
  function moveAisle(store,index,delta){const list=aislesForStore(store),target=index+delta;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];const all=aisleOrders();all[store]=list;saveAisleOrders(all);render();renderShopping()}
  select.onchange=render;render();
}
$('#manageAisles').onclick=()=>{renderAisleOrderEditor();$('#aisleOrderDialog').showModal()};
$('#closeAisleOrder').onclick=$('#doneAisleOrder').onclick=()=>$('#aisleOrderDialog').close();
function shoppingGroupKey(x){if(shoppingGroupMode==='store')return x.store||'Magasin à définir';if(shoppingGroupMode==='aisle')return x.aisle||'Rayon à définir';return (x.name?.[0]||'#').toUpperCase()}
function sortedShopping(){return [...shopping].sort((a,b)=>{
  let grouped=0;
  if(shoppingGroupMode==='store'){const storeCmp=(a.store||'zzz').localeCompare(b.store||'zzz','fr',{sensitivity:'base'});grouped=storeCmp||(aisleRank(a.store||'',a.aisle)-aisleRank(b.store||'',b.aisle))||(a.aisle||'zzz').localeCompare(b.aisle||'zzz','fr',{sensitivity:'base'});}
  else if(shoppingGroupMode==='aisle')grouped=(a.aisle||'zzz').localeCompare(b.aisle||'zzz','fr',{sensitivity:'base'});
  return grouped||a.name.localeCompare(b.name,'fr',{sensitivity:'base'});
})}
function shoppingRow(x){const amount=x.qty?`${Math.round(Number(x.qty)*100)/100} ${esc(x.unit)}`:x.text?`${esc(x.text)} ${esc(x.unit)}`:'';return `<div class="shop-item ${x.checked?'checked':''}" data-shopping-id="${esc(x.id)}"><input type="checkbox" data-shop-check="${esc(x.id)}" ${x.checked?'checked':''}><button class="shop-text" data-edit-shopping="${esc(x.id)}"><strong>${esc(x.name)}</strong>${amount?` <span>— ${amount}</span>`:''}</button></div>`}
function renderStoreSubgroups(items){const aisles={};items.forEach(x=>(aisles[x.aisle||'Rayon à définir']??=[]).push(x));const store=items[0]?.store||'';return Object.entries(aisles).sort((a,b)=>aisleRank(store,a[0])-aisleRank(store,b[0])).map(([aisle,list])=>`<div class="shop-subgroup"><h4>${esc(aisle)}</h4>${list.map(shoppingRow).join('')}</div>`).join('')}
function renderShopping(){
  shopping=shopping.map(normalizeShoppingItem);
  const remaining=shopping.filter(x=>!x.checked).length;$('#shoppingSummary').textContent=`${remaining} à acheter · ${shopping.length} au total`;
  if(!shopping.length){$('#shoppingList').innerHTML='<p class="muted">La liste est vide.</p>';refreshShoppingSuggestions();return}
  const groups={};sortedShopping().forEach(x=>(groups[shoppingGroupKey(x)]??=[]).push(x));
  $('#shoppingList').innerHTML=Object.entries(groups).map(([name,items])=>`<section class="shop-group"><h3>${esc(name)}</h3>${shoppingGroupMode==='store'?renderStoreSubgroups(items):items.map(shoppingRow).join('')}</section>`).join('');
  $$('[data-shop-check]').forEach(c=>c.onchange=()=>{const x=shopping.find(i=>i.id===c.dataset.shopCheck);if(x){x.checked=c.checked;saveShopping();renderShopping()}});
  $$('[data-edit-shopping]').forEach(b=>b.onclick=()=>openShopping(b.dataset.editShopping));refreshShoppingSuggestions();
}
function addSelectOption(select,value){if(value&&!Array.from(select.options).some(o=>o.value===value)){const option=document.createElement('option');option.value=value;option.textContent=value;select.insertBefore(option,select.querySelector('option[value="__other__"]'))}}function rememberedShoppingStores(){try{return JSON.parse(localStorage.getItem(shoppingStoreMemory)||'[]')||[]}catch{return[]}}function rememberShoppingStore(value){const v=String(value||'').trim();if(!v)return;const list=[...new Set([...rememberedShoppingStores(),v])].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));localStorage.setItem(shoppingStoreMemory,JSON.stringify(list))}function refreshShoppingSuggestions(){const assignmentStores=Object.values(shoppingAssignments()).map(x=>x.store).filter(Boolean),stores=[...new Set([...rememberedShoppingStores(),...assignmentStores,...shopping.map(x=>x.store).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'})),aisles=[...new Set(shopping.map(x=>x.aisle).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));stores.forEach(x=>addSelectOption($('#shoppingStore'),x));aisles.forEach(x=>addSelectOption($('#shoppingAisle'),x))}function handleOtherSelect(select,label){if(select.value==='__other__'){const value=prompt(`Nouveau ${label} :`);if(value?.trim()){addSelectOption(select,value.trim());select.value=value.trim();if(label==='magasin')rememberShoppingStore(value.trim())}else select.value=''}}$('#shoppingStore').onchange=()=>handleOtherSelect($('#shoppingStore'),'magasin');$('#shoppingAisle').onchange=()=>handleOtherSelect($('#shoppingAisle'),'rayon');
function openShopping(id=''){const x=shopping.find(i=>i.id===id);$('#shoppingDialogTitle').textContent=x?'Modifier l’article':'Ajouter un article';$('#shoppingId').value=x?.id||'';$('#shoppingName').value=x?.name||'';$('#shoppingQty').value=x?.qty||x?.text||'';$('#shoppingUnit').value=x?.unit||'';addSelectOption($('#shoppingStore'),x?.store||'');addSelectOption($('#shoppingAisle'),x?.aisle||'');$('#shoppingStore').value=x?.store||'';$('#shoppingAisle').value=x?.aisle||'';$('#deleteShopping').classList.toggle('hidden',!x);$('#shoppingOrigins').classList.toggle('hidden',!x?.origins?.length);$('#shoppingOrigins').innerHTML=x?.origins?.length?`<strong>Origine :</strong><br>${x.origins.map(esc).join('<br>')}`:'';refreshShoppingSuggestions();$('#shoppingDialog').showModal()}
function addShopping(){openShopping()}
$('#shoppingForm').onsubmit=e=>{e.preventDefault();const id=$('#shoppingId').value,x=shopping.find(i=>i.id===id),raw=$('#shoppingQty').value.trim(),parsed=parseNumber(raw),item=normalizeShoppingItem({...(x||{}),id:id||uid(),name:$('#shoppingName').value.trim(),qty:typeof parsed==='number'?parsed:0,text:typeof parsed==='number'?'':raw,unit:$('#shoppingUnit').value.trim(),store:$('#shoppingStore').value.trim(),aisle:$('#shoppingAisle').value.trim(),manual:x?.manual??true,origins:x?.origins||['Ajout manuel']});if(x)Object.assign(x,item);else shopping.push(item);rememberShoppingStore(item.store);saveShopping();renderShopping();$('#shoppingDialog').close()};
$('#closeShopping').onclick=()=>$('#shoppingDialog').close();$('#deleteShopping').onclick=()=>{const id=$('#shoppingId').value;if(id&&confirm('Supprimer cet article ?')){shopping=shopping.filter(x=>x.id!==id);saveShopping();renderShopping();$('#shoppingDialog').close()}};
$('#addShopping').onclick=addShopping;$('#addShoppingBottom').onclick=addShopping;$('#clearChecks').onclick=()=>{shopping.forEach(x=>x.checked=false);saveShopping();renderShopping()};$('#removeChecked').onclick=()=>{const n=shopping.filter(x=>x.checked).length;if(!n)return alert('Aucun article coché.');if(confirm(`Supprimer ${n} article${n>1?'s':''} acheté${n>1?'s':''} ?`)){shopping=shopping.filter(x=>!x.checked);saveShopping();renderShopping()}};$('#clearShopping').onclick=()=>{if(confirm('Vider toute la liste ?')){shopping=[];saveShopping();renderShopping()}};
$$('[data-shop-group]').forEach(b=>b.onclick=()=>{shoppingGroupMode=b.dataset.shopGroup;$$('[data-shop-group]').forEach(x=>x.classList.toggle('active',x===b));renderShopping()});

// Import Paprika : .paprikarecipe (gzip JSON), .paprikarecipes (archive ZIP), JSON, HTML ou texte.
$('#importPaprika').onclick=()=>{pendingImport=[];$('#paprikaFile').value='';$('#importStatus').textContent='Aucun fichier analysé.';$('#importPreview').innerHTML='';$('#confirmImport').disabled=true;$('#importDialog').showModal()};$('#closeImport').onclick=$('#cancelImport').onclick=()=>$('#importDialog').close();
$('#paprikaFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#importStatus').textContent='Analyse en cours…';$('#confirmImport').disabled=true;try{pendingImport=await parseImportFile(file);$('#importStatus').innerHTML=`<strong>${pendingImport.length}</strong> recette${pendingImport.length>1?'s':''} reconnue${pendingImport.length>1?'s':''} dans ${esc(file.name)}.`;$('#importPreview').innerHTML=pendingImport.slice(0,12).map(r=>`<div class="import-row"><strong>${esc(r.title)}</strong><span>${esc(r.category)} · ${r.ingredients.length} ingrédients</span></div>`).join('')+(pendingImport.length>12?`<p class="muted">… et ${pendingImport.length-12} autres.</p>`:'');$('#confirmImport').disabled=!pendingImport.length;}catch(err){console.error(err);pendingImport=[];$('#importStatus').textContent=`Import impossible : ${err.message}`;$('#importPreview').innerHTML='';}};
$('#importForm').onsubmit=e=>{e.preventDefault();if(!pendingImport.length)return;const replace=$('#replaceDuplicates').checked,importTag=`Import du ${new Date().toLocaleDateString('fr-CH')}`;pendingImport=pendingImport.map(r=>({...r,tags:[...new Set([...(r.tags||[]),importTag])]}));let added=0,replaced=0,ignored=0;pendingImport.forEach(r=>{const i=recipes.findIndex(x=>(r.paprikaUid&&x.paprikaUid===r.paprikaUid)||norm(x.title)===norm(r.title));if(i>=0){if(replace){r.id=recipes[i].id;recipes[i]=r;replaced++}else ignored++}else{recipes.unshift(r);added++}});saveRecipes();fillCategories();renderRecipes();$('#importDialog').close();alert(`Import terminé : ${added} ajoutée(s), ${replaced} remplacée(s), ${ignored} ignorée(s).`)};
async function parseImportFile(file){const bytes=new Uint8Array(await file.arrayBuffer());return parseBytes(bytes,file.name)}
async function parseBytes(bytes,name='import'){
  if(bytes[0]===0x50&&bytes[1]===0x4b){const entries=await unzip(bytes);let out=[];for(const e of entries){if(/\.(paprikarecipe|json|txt)$/i.test(e.name)||!e.name.includes('.'))out.push(...await parseBytes(e.data,e.name));}return dedupeImported(out)}
  if(bytes[0]===0x1f&&bytes[1]===0x8b){const raw=await decompress(bytes,'gzip');return parseBytes(raw,name.replace(/\.paprikarecipe$/i,'.json'))}
  const text=new TextDecoder('utf-8').decode(bytes).replace(/^\uFEFF/,'').trim();if(!text)return[];
  if(/^</.test(text))return parseHtmlRecipes(text);
  const objects=[];try{const j=JSON.parse(text);objects.push(...(Array.isArray(j)?j:j.recipes&&Array.isArray(j.recipes)?j.recipes:[j]))}catch{for(const line of text.split(/\r?\n/)){try{const j=JSON.parse(line);objects.push(j)}catch{}}}
  if(!objects.length)throw new Error('format non reconnu');return dedupeImported(objects.map(mapPaprikaRecipe).filter(Boolean));
}
async function decompress(bytes,format){if(typeof DecompressionStream==='undefined')throw new Error('décompression non prise en charge par ce navigateur');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream(format));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function unzip(bytes){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('archive ZIP illisible');const count=dv.getUint16(eocd+10,true),central=dv.getUint32(eocd+16,true);let p=central,out=[];for(let n=0;n<count;n++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),csize=dv.getUint32(p+20,true),nlen=dv.getUint16(p+28,true),xlen=dv.getUint16(p+30,true),clen=dv.getUint16(p+32,true),local=dv.getUint32(p+42,true),name=new TextDecoder().decode(bytes.slice(p+46,p+46+nlen));const ln=dv.getUint16(local+26,true),lx=dv.getUint16(local+28,true),start=local+30+ln+lx,compressed=bytes.slice(start,start+csize);let data;if(method===0)data=compressed;else if(method===8)data=await decompress(compressed,'deflate-raw');else{p+=46+nlen+xlen+clen;continue}if(!name.endsWith('/'))out.push({name,data});p+=46+nlen+xlen+clen}return out}
function parseHtmlRecipes(text){const doc=new DOMParser().parseFromString(text,'text/html'),blocks=[...doc.querySelectorAll('[itemtype*="Recipe"], .recipe')];if(!blocks.length)blocks.push(doc.body);return blocks.map((b,i)=>mapPaprikaRecipe({name:b.querySelector('[itemprop="name"],h1,h2')?.textContent||`Recette importée ${i+1}`,ingredients:[...b.querySelectorAll('[itemprop="recipeIngredient"],.ingredient')].map(x=>x.textContent).join('\n'),directions:[...b.querySelectorAll('[itemprop="recipeInstructions"],.instructions li')].map(x=>x.textContent).join('\n'),source_url:location.href})).filter(Boolean)}
function mapPaprikaRecipe(p){if(!p||typeof p!=='object')return null;const title=String(p.name||p.title||'').trim();if(!title)return null;const categories=Array.isArray(p.categories)?p.categories:String(p.categories||p.category||'Importée').split(',');const ing=Array.isArray(p.ingredients)?p.ingredients.join('\n'):String(p.ingredients||'');const dir=Array.isArray(p.directions)?p.directions.join('\n'):String(p.directions||p.steps||'');const servings=parseInt(String(p.servings||4).match(/\d+/)?.[0]||'4',10);const time=parseDuration(p.total_time||p.cook_time||p.prep_time||p.time);return normalizeRecipe({id:slug(title),paprikaUid:p.uid||p.id||'',title,category:categories.map(x=>String(x).trim()).filter(Boolean)[0]||'Importée',time,servings,ingredients:ing.split(/\r?\n/).map(parseIngredientLine).filter(x=>x[0]),steps:dir.split(/\r?\n/).map(x=>x.replace(/^\s*\d+[.)-]?\s*/, '').trim()).filter(Boolean),tags:categories.map(x=>String(x).trim()).filter(Boolean),temperature:'les-deux',avecViande:false,source:p.source_url||p.source||'',notes:p.notes||p.description||''});}
function parseDuration(v){if(typeof v==='number')return v;const s=String(v||'');const h=+(s.match(/(\d+)\s*h/i)?.[1]||0),m=+(s.match(/(\d+)\s*m/i)?.[1]||0);if(h||m)return h*60+m;return +(s.match(/\d+/)?.[0]||0)}
const unitAliases={'tablespoon':'c. à soupe','tablespoons':'c. à soupe','tbsp':'c. à soupe','tbs':'c. à soupe','cas':'c. à soupe','teaspoon':'c. à café','teaspoons':'c. à café','tsp':'c. à café','cac':'c. à café','gram':'g','grams':'g','kilogram':'kg','kilograms':'kg','milliliter':'ml','milliliters':'ml','liter':'l','liters':'l'};
function parseIngredientLine(line){line=String(line).replace(/^[-•]\s*/,'').trim();if(!line)return['','',''];const m=line.match(/^((?:\d+\s+)?\d+\/\d+|\d+[.,]?\d*|[½¼¾⅓⅔])\s*([\p{L}. à]+)?\s+(.+)$/u);if(!m)return[line,'',''];let q=parseNumber(m[1]),unit=norm(m[2]||'').replace(/\.$/,'').trim(),name=m[3].trim();unit=unitAliases[unit]||m[2]?.trim()||'';return[name,q,unit]}
function dedupeImported(a){const seen=new Set();return a.filter(r=>{const k=r.paprikaUid||norm(r.title);if(seen.has(k))return false;seen.add(k);return true})}

function printDocument(title,body){const w=open('','_blank','width=900,height=700');if(!w)return alert('Fenêtre d’impression bloquée.');w.document.write(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{margin:10mm}body{font-family:Arial;max-width:850px;margin:auto;line-height:1.25}h1,h2{font-family:Georgia}.columns{display:grid;grid-template-columns:1fr 1.4fr;gap:20px}li{margin:3px 0}.day{border:1px solid #bbb;padding:8px;margin:6px 0;break-inside:avoid}.shop{columns:2}</style></head><body>${body}</body></html>`);w.document.close();setTimeout(()=>w.print(),250)}
function printRecipe(r,people=null){if(!r)return;const p=people||r.servings;const body=`<h1>${esc(r.title)}</h1><p>${r.time||'?'} min · ${p} personnes · ${esc(r.category)}</p><div class="columns"><section><h2>Ingrédients</h2><ul>${scaledIngredients(r,p).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><h2>Préparation</h2><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section></div>`;printDocument(r.title,body)}
$('#printPlan').onclick=()=>{const week=plan.filter(x=>x.date>=currentWeekStart&&x.date<=addDaysISO(currentWeekStart,6));if(!week.length)return alert('Aucun planning.');printDocument('Planning',`<h1>Calendrier culinaire — ${esc(weekLabel(currentWeekStart))}</h1>${days.map((d,i)=>{const date=addDaysISO(currentWeekStart,i),ms=week.filter(x=>x.date===date);return ms.length?`<div class="day"><h2>${esc(dateLabel(date))}</h2>${slots.map(s=>{const si=ms.filter(x=>x.slot===s);return si.length?`<h3>${s} — ${mealPeople(date,s)} pers.</h3>${si.map(m=>`<p>${m.role?`<strong>${esc(m.role)}</strong> · `:''}${esc(m.recipe.title)}</p>`).join('')}`:''}).join('')}</div>`:''}).join('')}`)};$('#printShopping').onclick=()=>{if(!shopping.length)return alert('Liste vide.');const grouped={};sortedShopping().forEach(x=>(grouped[shoppingGroupKey(x)]??=[]).push(x));printDocument('Courses',`<h1>Liste de courses</h1>${Object.entries(grouped).map(([g,items])=>`<div class="day"><h2>${esc(g)}</h2><ul>${items.map(x=>`<li>☐ ${esc(x.name)}${x.qty?` — ${Math.round(x.qty*100)/100} ${esc(x.unit)}`:''}${shoppingGroupMode==='store'&&x.aisle?` <small>(${esc(x.aisle)})</small>`:''}</li>`).join('')}</ul></div>`).join('')}`)};
function loadSaved(){try{const s=JSON.parse(localStorage.getItem(planStore)||localStorage.getItem('hg-plan-v26')||'null');if(s){$('#planTime').value=s.time||'';currentWeekStart=s.weekStart||localStorage.getItem(weekStore)||mondayISO(new Date());plan=(s.items||[]).map(x=>{const date=x.date||addDaysISO(currentWeekStart,Number(x.dayIndex)||0);return{uid:x.uid||uid(),date,slot:x.slot,people:(Number(x.people)>=1&&Number(x.people)<=10?Number(x.people):(Number(s.people)>=1&&Number(s.people)<=10?Number(s.people):null)),role:x.role||'',notes:x.notes||'',preparePreviousDay:Boolean(x.preparePreviousDay),recipe:recipes.find(r=>r.id===x.id)}}).filter(x=>x.recipe)}shopping=(JSON.parse(localStorage.getItem(shoppingStore)||localStorage.getItem('hg-shopping-v26')||localStorage.getItem('hg-shopping')||'[]')||[]).map(normalizeShoppingItem)}catch(e){console.error(e)}localStorage.setItem(weekStore,currentWeekStart);renderDaySlotChoices();renderPlan();renderShopping()}

// Sauvegarde et transfert entre appareils
let pendingDataImport = null;
function herbierStorageSnapshot(){
  const data={};
  for(let i=0;i<localStorage.length;i++){
    const key=localStorage.key(i);
    if(key && key.startsWith('hg-') && key!==EMERGENCY_BACKUP_KEY) data[key]=localStorage.getItem(key);
  }
  // Garantit que les collections actuellement chargées figurent dans la sauvegarde.
  data[recipeStore]=JSON.stringify(recipes);
  if(typeof restaurants!=='undefined' && Array.isArray(restaurants)) data[restaurantStore]=JSON.stringify(restaurants);
  if(typeof producers!=='undefined' && Array.isArray(producers)) data[producerStore]=JSON.stringify(producers);
  if(typeof herbs!=='undefined' && Array.isArray(herbs)) data[herbStore]=JSON.stringify(herbs);
  return {format:'HerbierGourmandBackup',formatVersion:1,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),data};
}
function downloadTextFile(filename,text){
  const blob=new Blob([text],{type:'application/json;charset=utf-8'});
  const url=URL.createObjectURL(blob),a=document.createElement('a');
  a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function backupFilename(){
  const d=new Date(),pad=n=>String(n).padStart(2,'0');
  return `Herbier_Gourmand_${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}.hgbak`;
}
function backupMeta(){try{return JSON.parse(localStorage.getItem(BACKUP_META_KEY)||'null')}catch{return null}}
function updateBackupReminder(){
  const el=$('#backupReminder');if(!el)return;
  const meta=backupMeta(),changes=Number(localStorage.getItem(CHANGE_COUNTER_KEY)||0);
  if(!meta){el.textContent='Conseil : crée une première sauvegarde et range-la dans ton dossier OneDrive.';return}
  const when=new Date(meta.at).toLocaleString('fr-FR');
  el.textContent=`Dernière sauvegarde : ${when}${changes?` · ${changes} modification${changes>1?'s':''} depuis`:''}.`;
}
function registerProtectedChange(){
  const n=Number(localStorage.getItem(CHANGE_COUNTER_KEY)||0)+1;
  localStorage.setItem(CHANGE_COUNTER_KEY,String(n));updateBackupReminder();
}
function markBackupCreated(filename){
  localStorage.setItem(BACKUP_META_KEY,JSON.stringify({at:new Date().toISOString(),filename}));
  localStorage.setItem(CHANGE_COUNTER_KEY,'0');clearDirty();updateBackupReminder();
}
function createEmergencyCheckpoint(reason='opération sensible'){
  const snapshot=herbierStorageSnapshot();
  const record={reason,createdAt:new Date().toISOString(),snapshot};
  localStorage.setItem(EMERGENCY_BACKUP_KEY,JSON.stringify(record));
  return snapshot;
}
$('#exportData').onclick=()=>{
  try{
    const backup=herbierStorageSnapshot(),filename=backupFilename();
    downloadTextFile(filename,JSON.stringify(backup,null,2));markBackupCreated(filename);
    $('#dataTransferStatus').textContent=`Sauvegarde créée : ${Object.keys(backup.data).length} ensemble(s) de données. Range le fichier dans OneDrive/Herbier Gourmand/Sauvegardes.`;
  }catch(err){console.error(err);alert('Impossible de créer la sauvegarde.');}
};
$('#importData').onclick=()=>{$('#dataImportFile').value='';$('#dataImportFile').click()};
$('#dataImportFile').onchange=async e=>{
  const file=e.target.files?.[0];if(!file)return;
  try{
    const parsed=JSON.parse(await file.text());
    if(parsed?.format!=='HerbierGourmandBackup'||parsed?.formatVersion!==1||!parsed.data||typeof parsed.data!=='object')throw new Error('format de sauvegarde non reconnu');
    const keys=Object.keys(parsed.data).filter(k=>k.startsWith('hg-')&&typeof parsed.data[k]==='string');
    if(!keys.length)throw new Error('aucune donnée Herbier Gourmand trouvée');
    pendingDataImport={...parsed,data:Object.fromEntries(keys.map(k=>[k,parsed.data[k]]))};
    let recipeCount='inconnu',shoppingCount='inconnu',planCount='inconnu';
    try{recipeCount=JSON.parse(pendingDataImport.data[recipeStore]||'[]').length}catch{}
    try{shoppingCount=JSON.parse(pendingDataImport.data[shoppingStore]||'[]').length}catch{}
    try{planCount=(JSON.parse(pendingDataImport.data[planStore]||'{}').items||[]).length}catch{}
    const when=parsed.exportedAt?new Date(parsed.exportedAt).toLocaleString('fr-FR'):'date inconnue';
    $('#dataImportSummary').innerHTML=`<strong>Sauvegarde du ${esc(when)}</strong><br>${recipeCount} recette(s) · ${planCount} repas planifié(s) · ${shoppingCount} article(s) de courses.<br><span class="muted">Les données actuelles de cet appareil seront remplacées.</span>`;
    $('#dataImportDialog').showModal();
  }catch(err){console.error(err);pendingDataImport=null;alert(`Import impossible : ${err.message}`);}
};
$('#closeDataImport').onclick=$('#cancelDataImport').onclick=()=>{$('#dataImportDialog').close();pendingDataImport=null};
$('#dataImportForm').onsubmit=e=>{
  e.preventDefault();if(!pendingDataImport)return;
  try{
    // Double protection : point de restauration local + téléchargement avant remplacement.
    const safety=createEmergencyCheckpoint('avant import'),safetyName=backupFilename().replace('.hgbak','_avant-import.hgbak');
    downloadTextFile(safetyName,JSON.stringify(safety,null,2));
    const currentHgKeys=[];
    for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('hg-')&&key!==EMERGENCY_BACKUP_KEY)currentHgKeys.push(key)}
    currentHgKeys.forEach(key=>localStorage.removeItem(key));
    Object.entries(pendingDataImport.data).forEach(([key,value])=>localStorage.setItem(key,value));
    localStorage.setItem(BACKUP_META_KEY,JSON.stringify({at:pendingDataImport.exportedAt||new Date().toISOString(),filename:'sauvegarde importée'}));
    localStorage.setItem(CHANGE_COUNTER_KEY,'0');
    $('#dataImportDialog').close();
    alert('Import terminé. Une sauvegarde « avant import » a aussi été téléchargée. Herbier Gourmand va maintenant recharger les données.');
    location.reload();
  }catch(err){console.error(err);alert('Impossible d’importer les données. Le point de restauration local a été conservé lorsque sa création a réussi.');}
};


// v2.7 — partage, lecture seule, GitHub et producteurs locaux
const producerStore='hg-producers-v27';
const READONLY=new URLSearchParams(location.search).get('readonly')==='1';
let producers=[],viewedProducerId=null,previousProducerView='producers',dirty=false;
function markDirty(){dirty=true;document.body.classList.add('has-unsaved');const el=$('#saveState');if(el){el.textContent='Modifications non sauvegardées';el.classList.add('dirty')}}
function clearDirty(){dirty=false;document.body.classList.remove('has-unsaved');const el=$('#saveState');if(el){el.textContent='À jour';el.classList.remove('dirty')}}
addEventListener('beforeunload',e=>{if(dirty&&!READONLY){e.preventDefault();e.returnValue='';}});
function inferredGithubConfig(){const host=location.hostname,parts=location.pathname.split('/').filter(Boolean);return {owner:host.endsWith('.github.io')?host.split('.')[0]:'',repo:parts[0]||'',branch:'main',path:'herbier-latest.hgbak'};}
function githubConfig(){try{return {...inferredGithubConfig(),...JSON.parse(localStorage.getItem('hg-github-config-v27')||'{}')}}catch{return inferredGithubConfig()}}
async function autoLoadSharedBackup(){if(!READONLY)return;try{const r=await fetch(`herbier-latest.hgbak?_=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const b=await r.json();if(b?.format!=='HerbierGourmandBackup'||!b.data)return;Object.entries(b.data).forEach(([k,v])=>{if(k.startsWith('hg-')&&typeof v==='string')localStorage.setItem(k,v)});sessionStorage.setItem('hg-readonly-loaded',b.exportedAt||'loaded');}catch(e){console.warn('Sauvegarde partagée indisponible',e)}}
function applyReadonlyMode(){if(!READONLY)return;document.body.classList.add('readonly-mode');document.querySelector('header p').textContent+=' · Lecture seule';['#newRecipe','#importPaprika','#newRestaurant','#newProducer','#savePlan','#buildShopping','#addShopping','#addShoppingBottom','#clearChecks','#removeChecked','#clearShopping','#exportData','#importData','#saveToGithub','#githubSettings','#manageAisles'].forEach(s=>{const e=$(s);if(e)e.classList.add('hidden')});$$('[data-edit],[data-edit-restaurant],#editViewedRecipe,#editViewedRestaurant,#editViewedProducer,#editViewedHerb,#editViewedProduce,.restaurant-card-edit,.producer-card-edit').forEach(e=>e.classList.add('hidden'));}
$('#openReadonly').onclick=()=>open(`${location.origin}${location.pathname}?readonly=1`,'_blank');
$('#githubSettings').onclick=()=>{const c=githubConfig();$('#githubOwner').value=c.owner;$('#githubRepo').value=c.repo;$('#githubBranch').value=c.branch;$('#githubPath').value=c.path;$('#githubToken').value=sessionStorage.getItem('hg-github-token-v27')||'';$('#githubDialog').showModal()};
$('#closeGithub').onclick=$('#cancelGithub').onclick=()=>$('#githubDialog').close();
$('#githubForm').onsubmit=e=>{e.preventDefault();const c={owner:$('#githubOwner').value.trim(),repo:$('#githubRepo').value.trim(),branch:$('#githubBranch').value.trim(),path:$('#githubPath').value.trim()};localStorage.setItem('hg-github-config-v27',JSON.stringify(c));sessionStorage.setItem('hg-github-token-v27',$('#githubToken').value.trim());$('#githubDialog').close();$('#githubStatus').textContent='Configuration enregistrée pour ce navigateur.'};
function bytesToBase64(text){return btoa(unescape(encodeURIComponent(text)))}
async function githubPutFile(path,text,message){const c=githubConfig(),token=sessionStorage.getItem('hg-github-token-v27');if(!c.owner||!c.repo||!token)throw new Error('Configuration GitHub ou jeton manquant');const url=`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(c.branch)}`;let sha='';const old=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`}});if(old.ok)sha=(await old.json()).sha||'';else if(old.status!==404)throw new Error(`Lecture GitHub impossible (${old.status})`);const body={message,content:bytesToBase64(text),branch:c.branch,...(sha?{sha}:{})};const put=await fetch(url.split('?')[0],{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!put.ok)throw new Error(`Enregistrement GitHub impossible (${put.status})`);return put.json();}
$('#saveToGithub').onclick=async()=>{try{const btn=$('#saveToGithub');btn.disabled=true;$('#githubStatus').textContent='Sauvegarde en cours…';const snap=herbierStorageSnapshot(),text=JSON.stringify(snap,null,2),c=githubConfig(),d=new Date(),pad=n=>String(n).padStart(2,'0'),dated=`backups/Herbier_Gourmand_${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}.hgbak`;await githubPutFile(c.path,text,`Herbier Gourmand : sauvegarde ${d.toLocaleString('fr-FR')}`);await githubPutFile(dated,text,`Herbier Gourmand : archive ${d.toLocaleString('fr-FR')}`);markBackupCreated(c.path);clearDirty();$('#githubStatus').textContent='Sauvegarde GitHub terminée. La version en lecture seule est à jour.';btn.disabled=false;}catch(e){console.error(e);$('#githubStatus').textContent=e.message;$('#saveToGithub').disabled=false;}};

function normalizeProducer(p={}){return {id:String(p.id||slug(p.name||'producteur')),name:String(p.name||'Producteur sans nom'),type:String(p.type||''),categories:Array.isArray(p.categories)?p.categories:[],region:String(p.region||''),city:String(p.city||''),address:String(p.address||''),postalCode:String(p.postalCode||''),country:String(p.country||'Suisse'),phone:String(p.phone||''),website:String(p.website||''),hours:String(p.hours||''),products:Array.isArray(p.products)?p.products:[],featuredProducts:Array.isArray(p.featuredProducts)?p.featuredProducts:[],salesModes:Array.isArray(p.salesModes)?p.salesModes:[],labels:Array.isArray(p.labels)?p.labels:[],tags:Array.isArray(p.tags)?p.tags:[],notes:String(p.notes||''),description:String(p.description||''),services:String(p.services||''),directSale:String(p.directSale||''),source:String(p.source||'')};}
function saveProducers(){localStorage.setItem(producerStore,JSON.stringify(producers));registerProtectedChange();markDirty()}
async function initProducers(){try{const stored=JSON.parse(localStorage.getItem(producerStore)||'null');if(stored)producers=stored;else{const r=await fetch(`producers.json?_=${Date.now()}`,{cache:'no-store'});producers=r.ok?await r.json():[];localStorage.setItem(producerStore,JSON.stringify(producers))}producers=producers.map(normalizeProducer);renderProducerFilters();refreshProducerCitySuggestions();renderProducers()}catch(e){console.error(e);producers=[];renderProducers()}}
function producerTerms(p){return [...new Set([...(p.products||[]),...(p.featuredProducts||[]),...(p.tags||[]),...(p.categories||[]),...(p.salesModes||[]),...(p.labels||[])].map(x=>String(x||'').trim()).filter(Boolean))]}
function producerTypes(p){return [...new Set([p.type,...(p.categories||[])].map(x=>String(x||'').trim()).filter(Boolean))]}
function producerValues(field){return [...new Set(producers.flatMap(p=>field==='tags'?producerTerms(p):field==='type'?producerTypes(p):[p[field]]).map(x=>String(x||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}))}
function fillProducerSelect(id,values,label){const e=$(id),v=e.value;e.innerHTML=`<option value="">${label}</option>`+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(values.includes(v))e.value=v}
function renderProducerFilters(){fillProducerSelect('#producerRegion',producerValues('region'),'Toutes les régions');fillProducerSelect('#producerCity',producerValues('city'),'Tous les lieux');fillProducerSelect('#producerType',producerValues('type'),'Tous les types');fillProducerSelect('#producerTag',producerValues('tags'),'Tous les produits')}
function filteredProducers(){const q=norm($('#producerSearch').value),region=$('#producerRegion').value,city=$('#producerCity').value,type=$('#producerType').value,tag=$('#producerTag').value;return producers.filter(p=>(!q||norm(JSON.stringify(p)).includes(q))&&(!region||p.region===region)&&(!city||p.city===city)&&(!type||producerTypes(p).includes(type))&&(!tag||producerTerms(p).includes(tag))).sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}))}
function producerCard(p){return `<article class="restaurant-card producer-card"><button class="restaurant-card-main" data-view-producer="${esc(p.id)}"><div class="meta">${esc([p.type,p.city,p.region].filter(Boolean).join(' · '))}</div><h3>${esc(p.name)}</h3><div class="badges">${producerTerms(p).slice(0,6).map(t=>`<span>${esc(t)}</span>`).join('')}</div></button><button class="restaurant-card-edit producer-card-edit" data-edit-producer="${esc(p.id)}">Modifier</button></article>`}
function renderProducers(){const list=filteredProducers();$('#producerCount').textContent=`${list.length} adresse${list.length>1?'s':''}`;$('#producerList').innerHTML=list.map(producerCard).join('')||'<p>Aucun producteur trouvé.</p>';$$('[data-view-producer]').forEach(b=>b.onclick=()=>showProducer(b.dataset.viewProducer,'producers'));$$('[data-edit-producer]').forEach(b=>b.onclick=()=>openProducer(b.dataset.editProducer));if(READONLY)applyReadonlyMode()}
['#producerSearch','#producerRegion','#producerCity','#producerType','#producerTag'].forEach(id=>{const e=$(id);e.addEventListener(e.tagName==='INPUT'?'input':'change',renderProducers)});$('#clearProducerFilters').onclick=()=>{$('#producerSearch').value='';$('#producerRegion').value='';$('#producerCity').value='';$('#producerType').value='';$('#producerTag').value='';renderProducers()};
function showProducer(id,from=''){const p=producers.find(x=>x.id===id);if(!p)return;if(from){rememberScroll(from);previousProducerView=from}else if(!previousProducerView)previousProducerView='producers';viewedProducerId=id;const rawAddress=String(p.address||'').trim(),addressNorm=norm(rawAddress),locality=[p.postalCode,p.city].filter(Boolean).join(' '),localityAlready=locality&&addressNorm.includes(norm(locality)),countryAlready=p.country&&addressNorm.includes(norm(p.country));const addressParts=[];if(rawAddress)addressParts.push(esc(rawAddress));if(locality&&!localityAlready)addressParts.push(esc(locality));if(p.country&&!countryAlready)addressParts.push(esc(p.country));const address=addressParts.join('<br>');$('#producerViewContent').innerHTML=`<div class="restaurant-detail-head"><div class="meta">${esc([p.type,p.region].filter(Boolean).join(' · '))}</div><h2>${esc(p.name)}</h2></div><div class="restaurant-detail-grid"><section><h3>Coordonnées</h3>${address?`<p>${address}</p>`:''}${p.phone?`<p><a href="tel:${esc(p.phone.replace(/\s/g,''))}">${esc(p.phone)}</a></p>`:''}${p.website?`<p>${linkMarkup(p.website,'Ouvrir le site internet')}</p>`:''}</section><section><h3>Horaires</h3><p>${p.hours?esc(p.hours).replace(/\n/g,'<br>'):'À compléter'}</p></section><section><h3>Produits proposés</h3><div class="badges">${producerTerms(p).map(t=>`<span>${esc(t)}</span>`).join('')||'À compléter'}</div></section><section><h3>Remarques</h3><p>${p.directSale?`<strong>Vente directe :</strong> ${esc(p.directSale)}<br>`:''}${p.notes?esc(p.notes).replace(/\n/g,'<br>'):'—'}</p></section></div>`;switchView('producerView')}
$('#backFromProducer').onclick=()=>switchView(previousProducerView);$('#editViewedProducer').onclick=()=>openProducer(viewedProducerId);
function openProducer(id){if(READONLY)return;const p=producers.find(x=>x.id===id);$('#producerDialogTitle').textContent=p?'Modifier le producteur':'Nouveau producteur';$('#producerId').value=p?.id||'';$('#producerName').value=p?.name||'';fillEditableSelect($('#producerTypeField'),producerValues('type'),p?.type||'','Choisir…');fillEditableSelect($('#producerRegionField'),producerValues('region'),p?.region||'','Choisir…');refreshProducerCitySuggestions();$('#producerCityField').value=p?.city||'';$('#producerAddress').value=p?.address||'';$('#producerPostal').value=p?.postalCode||'';$('#producerCountry').value=p?.country||'Suisse';$('#producerPhone').value=p?.phone||'';$('#producerWebsite').value=p?.website||'';$('#producerDirectSale').value=p?.directSale||'';$('#producerHours').value=p?.hours||'';$('#producerProducts').value=producerTerms(p||{}).join(', ');$('#producerNotes').value=p?.notes||'';$('#deleteProducer').classList.toggle('hidden',!p);$('#duplicateProducer').classList.toggle('hidden',!p);$('#producerDialog').showModal()}
$('#newProducer').onclick=()=>openProducer();$('#closeProducer').onclick=()=>$('#producerDialog').close();
function producerFromForm(newId=''){const old=producers.find(x=>x.id===$('#producerId').value),tags=$('#producerProducts').value.split(',').map(x=>x.trim()).filter(Boolean);return normalizeProducer({...old,id:newId||$('#producerId').value||slug($('#producerName').value),name:$('#producerName').value.trim(),type:$('#producerTypeField').value.trim(),region:$('#producerRegionField').value.trim(),city:$('#producerCityField').value.trim(),address:$('#producerAddress').value.trim(),postalCode:$('#producerPostal').value.trim(),country:$('#producerCountry').value.trim(),phone:$('#producerPhone').value.trim(),website:$('#producerWebsite').value.trim(),directSale:$('#producerDirectSale').value.trim(),hours:$('#producerHours').value.trim(),products:tags,tags:[],notes:$('#producerNotes').value.trim()})}
$('#producerForm').onsubmit=e=>{e.preventDefault();const p=producerFromForm(),i=producers.findIndex(x=>x.id===p.id);if(i>=0)producers[i]=p;else producers.push(p);saveProducers();renderProducerFilters();refreshProducerCitySuggestions();renderProducers();$('#producerDialog').close();if(viewedProducerId===p.id)showProducer(p.id)};
$('#deleteProducer').onclick=()=>{const id=$('#producerId').value;if(id&&confirm('Supprimer définitivement ce producteur ?')){producers=producers.filter(p=>p.id!==id);saveProducers();renderProducerFilters();refreshProducerCitySuggestions();renderProducers();$('#producerDialog').close();switchView('producers')}};
$('#duplicateProducer').onclick=()=>{const p=producerFromForm(slug($('#producerName').value));p.name+=' (copie)';producers.push(p);saveProducers();renderProducerFilters();renderProducers();$('#producerDialog').close()};

async function checkForUpdate(){const status=$('#updateStatus');try{const remote=await fetch(`version.json?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());status.textContent=`À jour · v${remote.version}`}catch{status.textContent=`Hors connexion · v${APP_VERSION}`}}
let deferredPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
init().catch(e=>{console.error(e);alert('Impossible de démarrer Herbier Gourmand.')});


function fillEditableSelect(el,values,current='',empty='Choisir…'){if(!el)return;const list=[...new Set(values.map(x=>String(x||'').trim()).filter(Boolean))];if(current&&!list.includes(current))list.push(current);list.sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));el.innerHTML=`<option value="">${empty}</option>`+list.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')+'<option value="__other__">Autre…</option>';el.value=current||'';}
function refreshProducerCitySuggestions(){const list=$('#producerCitySuggestions');if(!list)return;list.innerHTML=producerValues('city').map(v=>`<option value="${esc(v)}"></option>`).join('')}

// v2.6 — Envie d’une sortie ?
const restaurantStore='hg-restaurants-v26';
let restaurants=[], viewedRestaurantId=null, previousRestaurantView='restaurants';
function normalizeRestaurant(r={}){return {id:String(r.id||slug(r.name||'restaurant')),name:String(r.name||'Restaurant sans nom'),tenant:String(r.tenant||''),address:String(r.address||''),postalCode:String(r.postalCode||''),city:String(r.city||''),country:String(r.country||''),region:String(r.region||''),phone:String(r.phone||''),phones:Array.isArray(r.phones)?r.phones:[],email:String(r.email||''),website:String(r.website||''),hours:String(r.hours||''),specialties:Array.isArray(r.specialties)?r.specialties:[],notes:String(r.notes||''),source:String(r.source||'')};}
function saveRestaurants(){localStorage.setItem(restaurantStore,JSON.stringify(restaurants));registerProtectedChange();markDirty();}
async function initRestaurants(){
  try{const stored=JSON.parse(localStorage.getItem(restaurantStore)||'null');if(stored)restaurants=stored;else{const res=await fetch(`restaurants.json?_=${Date.now()}`,{cache:'no-store'});restaurants=res.ok?await res.json():[];saveRestaurants();}restaurants=restaurants.map(normalizeRestaurant);renderRestaurantFilters();renderRestaurants();}
  catch(e){console.error(e);restaurants=[];renderRestaurants();}
}
function uniqueRestaurantValues(field){return [...new Set(restaurants.flatMap(r=>field==='specialties'?r.specialties:[r[field]]).map(x=>String(x||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));}
function fillRestaurantSelect(id,values,firstLabel){const el=$(id),current=el.value;el.innerHTML=`<option value="">${firstLabel}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(values.includes(current))el.value=current;}
function renderRestaurantFilters(){fillRestaurantSelect('#restaurantRegion',uniqueRestaurantValues('region'),'Toutes les régions');fillRestaurantSelect('#restaurantCity',uniqueRestaurantValues('city'),'Tous les lieux');fillRestaurantSelect('#restaurantCountry',uniqueRestaurantValues('country'),'Tous les pays');fillRestaurantSelect('#restaurantSpecialty',uniqueRestaurantValues('specialties'),'Toutes les spécialités');}
function restaurantFiltered(){const q=norm($('#restaurantSearch').value),region=$('#restaurantRegion').value,city=$('#restaurantCity').value,country=$('#restaurantCountry').value,tag=$('#restaurantSpecialty').value;return restaurants.filter(r=>(!q||norm(r.name).includes(q))&&(!region||r.region===region)&&(!city||r.city===city)&&(!country||r.country===country)&&(!tag||r.specialties.includes(tag))).sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}));}
function restaurantCard(r){const locality=[r.postalCode,r.city,r.country].filter(Boolean).join(' · '),hours=String(r.hours||'Horaires à compléter').replace(/\s*\n\s*/g,' · ');return `<article class="restaurant-card restaurant-card-compact"><button class="restaurant-card-main" data-view-restaurant="${esc(r.id)}"><div class="restaurant-line restaurant-line-main"><h3>${esc(r.name)}</h3><span class="meta">${esc(locality||'Lieu à compléter')}</span></div><div class="restaurant-line restaurant-line-info"><span class="restaurant-hours">${esc(hours)}</span><span class="badges restaurant-tags">${r.specialties.slice(0,5).map(t=>`<span>${esc(t)}</span>`).join('')}</span></div></button><button class="restaurant-card-edit" data-edit-restaurant="${esc(r.id)}">Modifier</button></article>`;}
function renderRestaurants(){const found=restaurantFiltered();$('#restaurantCount').textContent=`${found.length} adresse${found.length>1?'s':''}`;$('#restaurantList').innerHTML=found.map(restaurantCard).join('')||'<p>Aucun restaurant trouvé.</p>';$$('[data-view-restaurant]').forEach(b=>b.onclick=()=>showRestaurant(b.dataset.viewRestaurant,'restaurants'));$$('[data-edit-restaurant]').forEach(b=>b.onclick=()=>openRestaurant(b.dataset.editRestaurant));}
['#restaurantSearch','#restaurantRegion','#restaurantCity','#restaurantCountry','#restaurantSpecialty'].forEach(id=>{const el=$(id);el.addEventListener(el.tagName==='INPUT'?'input':'change',renderRestaurants)});
$('#clearRestaurantFilters').onclick=()=>{$('#restaurantSearch').value='';$('#restaurantRegion').value='';$('#restaurantCity').value='';$('#restaurantCountry').value='';$('#restaurantSpecialty').value='';renderRestaurants();};
function linkMarkup(url,label){if(!url)return'';let href=url;if(!/^https?:\/\//i.test(href))href='https://'+href;return `<a href="${esc(href)}" target="_blank" rel="noopener">${label}</a>`;}
function showRestaurant(id,from=''){const r=restaurants.find(x=>x.id===id);if(!r)return;if(from){rememberScroll(from);previousRestaurantView=from}else if(!previousRestaurantView)previousRestaurantView='restaurants';viewedRestaurantId=id;const address=[r.address,[r.postalCode,r.city].filter(Boolean).join(' '),r.country].filter(Boolean).map(esc).join('<br>');$('#restaurantViewContent').innerHTML=`<div class="restaurant-detail-head"><div><div class="meta">${esc([r.city,r.country].filter(Boolean).join(' · '))}</div><h2>${esc(r.name)}</h2>${r.tenant?`<p><strong>Tenancier :</strong> ${esc(r.tenant)}</p>`:''}</div></div><div class="restaurant-detail-grid"><section><h3>Coordonnées</h3>${address?`<p>${address}</p>`:''}${r.phone?`<p><a href="tel:${esc(r.phone.replace(/\s/g,''))}">${esc(r.phone)}</a></p>`:''}${r.email?`<p><a href="mailto:${esc(r.email)}">${esc(r.email)}</a></p>`:''}${r.website?`<p>${linkMarkup(r.website,'Ouvrir le site internet')}</p>`:''}</section><section><h3>Heures d’ouverture</h3><p>${r.hours?esc(r.hours).replace(/\n/g,'<br>'):'À compléter'}</p></section><section><h3>Spécialités</h3><div class="badges">${r.specialties.length?r.specialties.map(t=>`<span>${esc(t)}</span>`).join(''):'À compléter'}</div></section><section><h3>Remarques</h3><p>${r.notes?esc(r.notes).replace(/\n/g,'<br>'):'—'}</p></section></div>`;switchView('restaurantView');}
$('#backFromRestaurant').onclick=()=>switchView(previousRestaurantView);$('#editViewedRestaurant').onclick=()=>openRestaurant(viewedRestaurantId);
function openRestaurant(id){const r=restaurants.find(x=>x.id===id);$('#restaurantDialogTitle').textContent=r?'Modifier le restaurant':'Nouveau restaurant';$('#restaurantId').value=r?.id||'';$('#restaurantName').value=r?.name||'';$('#restaurantTenant').value=r?.tenant||'';$('#restaurantAddress').value=r?.address||'';$('#restaurantPostal').value=r?.postalCode||'';fillEditableSelect($('#restaurantRegionField'),uniqueRestaurantValues('region'),r?.region||'','Choisir…');fillEditableSelect($('#restaurantCityField'),uniqueRestaurantValues('city'),r?.city||'','Choisir…');fillEditableSelect($('#restaurantCountryField'),uniqueRestaurantValues('country'),r?.country||'Suisse','Choisir…');$('#restaurantPhone').value=r?.phone||'';$('#restaurantWebsite').value=r?.website||'';$('#restaurantHours').value=r?.hours||'';$('#restaurantSpecialties').value=(r?.specialties||[]).join(', ');$('#restaurantNotes').value=r?.notes||'';$('#deleteRestaurant').classList.toggle('hidden',!r);$('#duplicateRestaurant').classList.toggle('hidden',!r);$('#restaurantDialog').showModal();}
$('#newRestaurant').onclick=()=>openRestaurant();$('#closeRestaurant').onclick=()=>$('#restaurantDialog').close();
function restaurantFromForm(newId=''){const existing=restaurants.find(x=>x.id===$('#restaurantId').value);return normalizeRestaurant({...existing,id:newId||$('#restaurantId').value||slug($('#restaurantName').value),name:$('#restaurantName').value.trim(),tenant:$('#restaurantTenant').value.trim(),address:$('#restaurantAddress').value.trim(),postalCode:$('#restaurantPostal').value.trim(),region:$('#restaurantRegionField').value.trim(),city:$('#restaurantCityField').value.trim(),country:$('#restaurantCountryField').value.trim(),phone:$('#restaurantPhone').value.trim(),website:$('#restaurantWebsite').value.trim(),hours:$('#restaurantHours').value.trim(),specialties:$('#restaurantSpecialties').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('#restaurantNotes').value.trim()});}
$('#restaurantForm').onsubmit=e=>{e.preventDefault();const r=restaurantFromForm();const i=restaurants.findIndex(x=>x.id===r.id);if(i>=0)restaurants[i]=r;else restaurants.unshift(r);saveRestaurants();renderRestaurantFilters();renderRestaurants();$('#restaurantDialog').close();if(viewedRestaurantId===r.id)showRestaurant(r.id);};
$('#deleteRestaurant').onclick=()=>{const id=$('#restaurantId').value;if(id&&confirm('Supprimer définitivement ce restaurant ?')){restaurants=restaurants.filter(r=>r.id!==id);saveRestaurants();renderRestaurantFilters();renderRestaurants();$('#restaurantDialog').close();switchView('restaurants')}};
$('#duplicateRestaurant').onclick=()=>{const r=restaurantFromForm(`${slug($('#restaurantName').value)}-${Date.now()}`);r.name+=' (copie)';restaurants.unshift(r);saveRestaurants();renderRestaurantFilters();renderRestaurants();$('#restaurantDialog').close();};
updateBackupReminder();


// v2.8 Bloc B — Grand Herbier : Plantes & Épices
const herbStore='hg-herbs-spices-v28';
let herbs=[], herbKnowledge={accords:[],melanges:[],substitutions:[],techniques:[]}, viewedHerbId=null, previousHerbView='herbs';
function herbUnique(field){return [...new Set(herbs.map(h=>String(h[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));}
function refreshHerbEditorSelects(h={}){fillEditableSelect($('#herbEditFamily'),herbUnique('family'),h.family||'','Choisir…');fillEditableSelect($('#herbEditSeason'),herbUnique('season'),h.season||'','Choisir…');fillEditableSelect($('#herbEditIntensity'),herbUnique('intensity'),h.intensity||'','Choisir…');fillEditableSelect($('#herbEditForms'),herbUnique('forms'),h.forms||'','Choisir…');}
function fillHerbSelect(id,values,label){const e=$(id),v=e.value;e.innerHTML=`<option value="">${label}</option>`+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(values.includes(v))e.value=v;}
function renderHerbFilters(){fillHerbSelect('#herbFamily',herbUnique('family'),'Toutes les familles');fillHerbSelect('#herbSeason',herbUnique('season'),'Toutes les saisons');fillHerbSelect('#herbIntensity',herbUnique('intensity'),'Toutes les intensités');}
function normalizeHerb(h={}){return {...h,id:String(h.id||slug(h.name||'plante')),name:String(h.name||'Plante sans nom')};}
async function initHerbs(){
 try{
  const res=await fetch(`herbs-spices.json?_=${Date.now()}`,{cache:'no-store'}),payload=res.ok?await res.json():{herbs:[]};
  herbKnowledge={accords:payload.accords||[],melanges:payload.melanges||[],substitutions:payload.substitutions||[],techniques:payload.techniques||[]};
  const stored=JSON.parse(localStorage.getItem(herbStore)||'null');
  herbs=(stored&&stored.length?stored:payload.herbs||[]).map(normalizeHerb);
  if(!stored)localStorage.setItem(herbStore,JSON.stringify(herbs));
  renderHerbFilters();renderHerbs();
 }catch(e){console.error('Grand Herbier',e);herbs=[];renderHerbs();}
}
function herbFiltered(){const q=norm($('#herbSearch')?.value),family=$('#herbFamily')?.value||'',season=$('#herbSeason')?.value||'',intensity=$('#herbIntensity')?.value||'';return herbs.filter(h=>(!family||h.family===family)&&(!season||h.season===season)&&(!intensity||h.intensity===intensity)&&(!q||norm(Object.values(h).join(' ')).includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}));}
function herbCard(h){return `<article class="herb-card"><button data-view-herb="${esc(h.id)}"><div class="herb-card-title"><h3>${esc(h.name)}</h3><span class="meta">${esc([h.family,h.intensity].filter(Boolean).join(' · '))}</span></div><p>${esc(h.flavor||h.uses||'')}</p><div class="badges">${[h.season,h.origin,h.dishTypes].filter(Boolean).slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')}</div></button></article>`;}
function renderHerbs(){const found=herbFiltered(),count=$('#herbCount'),list=$('#herbList');if(!count||!list)return;count.textContent=`${found.length} plante${found.length>1?'s':''} et épice${found.length>1?'s':''}`;list.innerHTML=found.map(herbCard).join('')||'<p>Aucune plante ou épice trouvée.</p>';$$('[data-view-herb]').forEach(b=>b.onclick=()=>showHerb(b.dataset.viewHerb,'herbs'));}
['#herbSearch','#herbFamily','#herbSeason','#herbIntensity'].forEach(id=>{const e=$(id);if(e)e.addEventListener(e.tagName==='INPUT'?'input':'change',renderHerbs)});
if($('#clearHerbFilters'))$('#clearHerbFilters').onclick=()=>{$('#herbSearch').value='';$('#herbFamily').value='';$('#herbSeason').value='';$('#herbIntensity').value='';renderHerbs();};
if($('#randomHerb'))$('#randomHerb').onclick=()=>{if(herbs.length)showHerb(herbs[Math.floor(Math.random()*herbs.length)].id)};
function terms(s){return String(s||'').split(/[,;+]|\bou\b/gi).map(x=>norm(x)).filter(x=>x.length>2)}
function linkedRecipes(h){const ts=[h.name,...terms(h.name),...terms(h.idealFoods),...terms(h.uses)].filter(Boolean);return recipes.filter(r=>r.ingredients.some(i=>ts.some(t=>norm(i[0]).includes(t)||t.includes(norm(i[0]))))).slice(0,30);}
function matchingMixes(h){const n=norm(h.name).split(' ')[0];return herbKnowledge.melanges.filter(m=>norm(m['Proportions en volumes']).includes(n));}
function matchingSubstitutions(h){const n=norm(h.name).split(' ')[0];return herbKnowledge.substitutions.filter(s=>norm(s['Ingrédient manquant']).includes(n)||norm(s['Remplacement']).includes(n));}
function matchingAccords(h){const n=norm(h.name).split(' ')[0];return herbKnowledge.accords.filter(a=>norm(a['Herbes / épices conseillées']).includes(n));}
function fieldBlock(title,value){return value?`<section><h3>${title}</h3><p>${esc(value).replace(/\n/g,'<br>')}</p></section>`:'';}
function showHerb(id,from=''){const h=herbs.find(x=>x.id===id);if(!h)return;if(from){rememberScroll(from);previousHerbView=from}else if(!previousHerbView)previousHerbView='herbs';viewedHerbId=id;const rec=linkedRecipes(h),mix=matchingMixes(h),sub=matchingSubstitutions(h),acc=matchingAccords(h);$('#herbViewContent').innerHTML=`<div class="herb-detail-head"><div class="meta">${esc([h.family,h.origin,h.season].filter(Boolean).join(' · '))}</div><h2>${esc(h.name)}</h2><p class="herb-flavor">${esc(h.flavor||'')}</p><div class="badges">${[h.intensity,h.forms,h.worldCuisines].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="herb-detail-grid">${fieldBlock('Usages principaux',h.uses)}${fieldBlock('Aliments idéaux',h.idealFoods)}${fieldBlock('Associations recommandées',h.recommendedPairings)}${fieldBlock('À la cuisson',h.cookingBehavior)}${fieldBlock('Préparation conseillée',h.preparation)}${fieldBlock('Quantité indicative',h.quantity)}${fieldBlock('Substitution possible',h.substitution)}${fieldBlock('Erreur à éviter',h.avoid)}${fieldBlock('Conservation',h.conservation)}${fieldBlock('Où l’acheter en Suisse',h.whereToBuy)}${fieldBlock('Idées de recettes',h.recipeIdeas)}${fieldBlock('Astuce du chef',h.chefTip)}</div><section class="knowledge-links"><h3>Recettes de ton Herbier</h3><div class="link-list">${rec.length?rec.map(r=>`<button data-herb-recipe="${esc(r.id)}">${esc(r.title)}</button>`).join(''):'<p class="muted">Aucune correspondance automatique trouvée pour l’instant.</p>'}</div></section><section class="knowledge-links"><h3>Accords par aliment</h3>${acc.length?acc.map(a=>`<article><strong>${esc(a['Aliment principal'])}</strong><p>${esc(a['Techniques idéales'])} · ${esc(a['Association signature'])}</p></article>`).join(''):'<p class="muted">Aucun accord spécifique.</p>'}</section><section class="knowledge-links"><h3>Mélanges maison</h3>${mix.length?mix.map(m=>`<article><strong>${esc(m['Nom du mélange'])}</strong><p>${esc(m['Proportions en volumes'])}</p><small>${esc(m['Utilisations'])}</small></article>`).join(''):'<p class="muted">Aucun mélange référencé.</p>'}</section><section class="knowledge-links"><h3>Substitutions</h3>${sub.length?sub.map(s=>`<article><strong>${esc(s['Ingrédient manquant'])} → ${esc(s['Remplacement'])}</strong><p>${esc(s['Résultat attendu'])}</p></article>`).join(''):'<p class="muted">Voir aussi la substitution indiquée dans la fiche.</p>'}</section><section class="knowledge-links"><h3>Techniques utiles</h3>${herbKnowledge.techniques.map(t=>`<article><strong>${esc(t['Technique'])}</strong><p>${esc(t['Méthode'])}</p><small>${esc(t['Point de vigilance'])}</small></article>`).join('')}</section>`;$$('[data-herb-recipe]').forEach(b=>b.onclick=()=>showRecipe(b.dataset.herbRecipe,'herbView'));switchView('herbView',{top:true});}
function openHerbEditor(id=viewedHerbId){if(READONLY)return;const h=herbs.find(x=>x.id===id);if(!h)return;$('#herbEditId').value=h.id;refreshHerbEditorSelects(h);const map={Name:'name',Family:'family',Origin:'origin',Season:'season',Intensity:'intensity',Forms:'forms',Flavor:'flavor',Uses:'uses',IdealFoods:'idealFoods',Pairings:'recommendedPairings',Cooking:'cookingBehavior',Preparation:'preparation',Quantity:'quantity',Substitution:'substitution',Avoid:'avoid',Conservation:'conservation',Where:'whereToBuy',RecipeIdeas:'recipeIdeas',ChefTip:'chefTip'};Object.entries(map).forEach(([suffix,key])=>{$(`#herbEdit${suffix}`).value=h[key]||''});$('#herbDialog').showModal()}
if($('#editViewedHerb')) $('#editViewedHerb').onclick=()=>openHerbEditor(); if($('#closeHerbDialog')) $('#closeHerbDialog').onclick=()=>$('#herbDialog').close();
if($('#herbForm')) $('#herbForm').onsubmit=e=>{e.preventDefault();const id=$('#herbEditId').value,h=herbs.find(x=>x.id===id);if(!h)return;const map={Name:'name',Family:'family',Origin:'origin',Season:'season',Intensity:'intensity',Forms:'forms',Flavor:'flavor',Uses:'uses',IdealFoods:'idealFoods',Pairings:'recommendedPairings',Cooking:'cookingBehavior',Preparation:'preparation',Quantity:'quantity',Substitution:'substitution',Avoid:'avoid',Conservation:'conservation',Where:'whereToBuy',RecipeIdeas:'recipeIdeas',ChefTip:'chefTip'};Object.entries(map).forEach(([suffix,key])=>h[key]=$(`#herbEdit${suffix}`).value.trim());localStorage.setItem(herbStore,JSON.stringify(herbs));registerProtectedChange();markDirty();renderHerbFilters();renderHerbs();$('#herbDialog').close();showHerb(id)};
if($('#backFromHerb')) $('#backFromHerb').onclick=()=>switchView(previousHerbView);


// v2.9.1 — Producteurs consolidés
const produceStore='hg-fruits-vegetables-v282';
let produceItems=[], viewedProduceId=null, previousProduceView='produce';
function normalizeProduce(p={}){return {...p,id:String(p.id||slug(p.name||'produit')),name:String(p.name||'Produit sans nom')};}
function produceUnique(field){return [...new Set(produceItems.map(p=>String(p[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));}
function refreshProduceEditorSelects(p={}){fillEditableSelect($('#produceEditCategory'),produceUnique('category'),p.category||'','Choisir…');fillEditableSelect($('#produceEditSeason'),produceUnique('season'),p.season||'','Choisir…');}
function fillProduceSelect(id,values,label){const e=$(id),v=e?.value||'';if(!e)return;e.innerHTML=`<option value="">${label}</option>`+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(values.includes(v))e.value=v;}
function renderProduceFilters(){fillProduceSelect('#produceCategory',produceUnique('category'),'Toutes les catégories');fillProduceSelect('#produceSeason',produceUnique('season'),'Toutes les saisons');fillProduceSelect('#produceAvailability',produceUnique('availability'),'Toutes les disponibilités');}
async function initProduce(){
 try{
  const res=await fetch(`fruits-vegetables.json?_=${Date.now()}`,{cache:'no-store'}),payload=res.ok?await res.json():{products:[]};
  const stored=JSON.parse(localStorage.getItem(produceStore)||'null');
  produceItems=(stored&&stored.length?stored:payload.products||[]).map(normalizeProduce);
  if(!stored)localStorage.setItem(produceStore,JSON.stringify(produceItems));
  renderProduceFilters();
  renderProduce();
 }catch(e){console.error('Fruits & Légumes',e);produceItems=[];renderProduce();}
}
function produceFiltered(){const q=norm($('#produceSearch')?.value),category=$('#produceCategory')?.value||'',season=$('#produceSeason')?.value||'',availability=$('#produceAvailability')?.value||'';return produceItems.filter(p=>(!category||p.category===category)&&(!season||p.season===season)&&(!availability||p.availability===availability)&&(!q||norm(Object.values(p).join(' ')).includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}));}
function produceCard(p){return `<article class="produce-card"><button data-view-produce="${esc(p.id)}"><div class="produce-card-title"><h3>${esc(p.name)}</h3><span class="meta">${esc([p.category,p.season].filter(Boolean).join(' · '))}</span></div><p>${esc(p.description||p.uses||'')}</p><div class="badges">${[p.availability,p.preparation,p.conservation].filter(Boolean).slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')}</div></button></article>`;}
function renderProduce(){const found=produceFiltered(),count=$('#produceCount'),list=$('#produceList');if(!count||!list)return;count.textContent=`${found.length} produit${found.length>1?'s':''}`;list.innerHTML=found.map(produceCard).join('')||'<p>Aucun fruit ou légume trouvé.</p>';$$('[data-view-produce]').forEach(b=>b.onclick=()=>showProduce(b.dataset.viewProduce,'produce'));}
['#produceSearch','#produceCategory','#produceSeason','#produceAvailability'].forEach(id=>{const e=$(id);if(e)e.addEventListener(e.tagName==='INPUT'?'input':'change',renderProduce)});
if($('#clearProduceFilters'))$('#clearProduceFilters').onclick=()=>{$('#produceSearch').value='';$('#produceCategory').value='';$('#produceSeason').value='';$('#produceAvailability').value='';renderProduce();};
if($('#randomProduce'))$('#randomProduce').onclick=()=>{if(produceItems.length)showProduce(produceItems[Math.floor(Math.random()*produceItems.length)].id)};
function linkedProduceRecipes(p){const names=[p.name,...terms(p.name)].filter(Boolean);return recipes.filter(r=>r.ingredients.some(i=>names.some(t=>norm(i[0]).includes(t)||t.includes(norm(i[0]))))).slice(0,40);}
function linkedProduceHerbs(p){const hay=norm([p.pairings,p.benefitPairings,p.preparation,p.uses].join(' '));return herbs.filter(h=>{const base=norm(h.name).split(' ')[0];return base.length>2&&hay.includes(base)}).slice(0,24);}
function linkedProduceProducers(p){const n=norm(p.name).split(' ')[0];return producers.filter(x=>norm([...(x.products||[]),x.notes||''].join(' ')).includes(n)).slice(0,20);}
function showProduce(id,from=''){const p=produceItems.find(x=>x.id===id);if(!p)return;if(from){rememberScroll(from);previousProduceView=from}else if(!previousProduceView)previousProduceView='produce';viewedProduceId=id;const rec=linkedProduceRecipes(p),hs=linkedProduceHerbs(p),prod=linkedProduceProducers(p);$('#produceViewContent').innerHTML=`<div class="produce-detail-head"><div class="meta">${esc([p.category,p.season,p.availability].filter(Boolean).join(' · '))}</div><h2>${esc(p.name)}</h2>${p.latinName?`<p class="latin-name"><em>${esc(p.latinName)}</em></p>`:''}<p class="produce-description">${esc(p.description||'')}</p></div><div class="produce-detail-grid">${fieldBlock('Bienfaits',p.benefits)}${fieldBlock('À associer avec',p.pairings)}${fieldBlock('Associations renforçant les bienfaits',p.benefitPairings)}${fieldBlock('Modes de préparation',p.preparation)}${fieldBlock('Conservation',p.conservation)}${fieldBlock('Utilisations culinaires',p.uses)}${fieldBlock('Remarques',p.notes)}</div><section class="knowledge-links"><h3>Recettes de ton Herbier</h3><div class="link-list">${rec.length?rec.map(r=>`<button data-produce-recipe="${esc(r.id)}">${esc(r.title)}</button>`).join(''):'<p class="muted">Aucune correspondance automatique trouvée pour l’instant.</p>'}</div></section><section class="knowledge-links"><h3>Plantes & Épices associées</h3><div class="link-list">${hs.length?hs.map(h=>`<button data-produce-herb="${esc(h.id)}">${esc(h.name)}</button>`).join(''):'<p class="muted">Aucun lien automatique trouvé dans les accords de cette fiche.</p>'}</div></section><section class="knowledge-links"><h3>Producteurs locaux</h3><div class="link-list">${prod.length?prod.map(x=>`<button data-produce-producer="${esc(x.id)}">${esc(x.name)}</button>`).join(''):'<p class="muted">Aucun producteur correspondant automatiquement pour l’instant.</p>'}</div></section>`;$$('[data-produce-recipe]').forEach(b=>b.onclick=()=>showRecipe(b.dataset.produceRecipe,'produceView'));$$('[data-produce-herb]').forEach(b=>b.onclick=()=>showHerb(b.dataset.produceHerb,'produceView'));$$('[data-produce-producer]').forEach(b=>b.onclick=()=>showProducer(b.dataset.produceProducer,'produceView'));switchView('produceView',{top:true});}
function openProduceEditor(id=viewedProduceId){if(READONLY)return;const p=produceItems.find(x=>x.id===id);if(!p)return;$('#produceEditId').value=p.id;refreshProduceEditorSelects(p);const map={Name:'name',Category:'category',Latin:'latinName',Availability:'availability',Season:'season',Description:'description',Benefits:'benefits',Pairings:'pairings',BenefitPairings:'benefitPairings',Preparation:'preparation',Conservation:'conservation',Uses:'uses',Notes:'notes'};Object.entries(map).forEach(([suffix,key])=>{$(`#produceEdit${suffix}`).value=p[key]||''});$('#produceDialog').showModal()}
if($('#editViewedProduce')) $('#editViewedProduce').onclick=()=>openProduceEditor(); if($('#closeProduceDialog')) $('#closeProduceDialog').onclick=()=>$('#produceDialog').close();
if($('#produceForm')) $('#produceForm').onsubmit=e=>{e.preventDefault();const id=$('#produceEditId').value,p=produceItems.find(x=>x.id===id);if(!p)return;const map={Name:'name',Category:'category',Latin:'latinName',Availability:'availability',Season:'season',Description:'description',Benefits:'benefits',Pairings:'pairings',BenefitPairings:'benefitPairings',Preparation:'preparation',Conservation:'conservation',Uses:'uses',Notes:'notes'};Object.entries(map).forEach(([suffix,key])=>p[key]=$(`#produceEdit${suffix}`).value.trim());localStorage.setItem(produceStore,JSON.stringify(produceItems));registerProtectedChange();markDirty();renderProduceFilters();renderProduce();$('#produceDialog').close();showProduce(id)};
if($('#backFromProduce')) $('#backFromProduce').onclick=()=>switchView(previousProduceView);



function bindEditableOtherSelect(selector,label){const el=$(selector);if(!el)return;el.addEventListener('change',()=>{if(el.value==='__other__'){const value=prompt(`Nouveau ${label} :`);if(value?.trim()){addSelectOption(el,value.trim());el.value=value.trim()}else el.value=''}})}
['#recipeCategory','#restaurantRegionField','#restaurantCityField','#restaurantCountryField','#producerTypeField','#producerRegionField','#herbEditFamily','#herbEditSeason','#herbEditIntensity','#herbEditForms','#produceEditCategory','#produceEditSeason'].forEach((id,i)=>bindEditableOtherSelect(id,['catégorie','région','lieu','pays','type','région','famille','saison','intensité','forme','catégorie','saison'][i]));
