let R=[],plan=[],shop=[];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],days=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function view(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===id));scrollTo(0,0)}$$('nav button').forEach(b=>b.onclick=()=>view(b.dataset.v));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));
function card(r){return `<article class="recipe"><div class="meta">${r.category} · ${r.time} min · ${r.servings} pers.</div><h3>${r.title}</h3><details><summary>Voir la recette</summary><h4>Ingrédients</h4><ul>${r.ingredients.map(i=>`<li>${i[0]} : ${i[1]} ${i[2]}</li>`).join('')}</ul><h4>Préparation</h4><ol>${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details></article>`}
function renderRecipes(){let q=norm($('#search').value),c=$('#cat').value,t=+$('#time').value||999;$('#recipeList').innerHTML=R.filter(r=>(!c||r.category===c)&&r.time<=t&&(!q||norm(JSON.stringify(r)).includes(q))).map(card).join('')||'<p>Aucune recette.</p>'}$('#search').oninput=renderRecipes;$('#cat').onchange=renderRecipes;$('#time').onchange=renderRecipes;
function pick(def=false){let max=+$('#planTime').value||999,pool=R.filter(r=>r.time<=max);if(pool.length<7)pool=R;if(def){let ids=['poulet-thym','boeuf-champi','gratin-courgettes','porc-moutarde','chili','agneau','poulet-creme'];plan=ids.map(id=>R.find(r=>r.id===id))}else plan=[...pool].sort(()=>Math.random()-.5).slice(0,7);renderPlan()}$('#generate').onclick=()=>pick();$('#default').onclick=()=>pick(true);
function renderPlan(){let people=+$('#people').value||4;$('#week').innerHTML=plan.map((r,i)=>`<article class="day"><div class="daytop"><div><div class="meta">${days[i]} · ${r.time} min</div><h3>${r.title}</h3></div><button data-r="${i}">Remplacer</button></div><select data-s="${i}">${R.map(x=>`<option value="${x.id}" ${x.id===r.id?'selected':''}>${x.title}</option>`).join('')}</select><details><summary>Voir la recette</summary><ul>${r.ingredients.map(x=>`<li>${x[0]} : ${Math.round((x[1]*people/r.servings)*10)/10} ${x[2]}</li>`).join('')}</ul><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></details></article>`).join('');$$('[data-s]').forEach(s=>s.onchange=()=>{plan[+s.dataset.s]=R.find(r=>r.id===s.value);renderPlan()});$$('[data-r]').forEach(b=>b.onclick=()=>{let i=+b.dataset.r,o=R.filter(r=>!plan.includes(r));plan[i]=o[Math.floor(Math.random()*o.length)]||R[0];renderPlan()})}$('#people').onchange=()=>plan.length&&renderPlan();
$('#save').onclick=()=>{localStorage.setItem('hgplan',JSON.stringify({p:+$('#people').value,ids:plan.map(x=>x.id)}));alert('Planning enregistré.')};$('#build').onclick=()=>{if(!plan.length)return alert('Génère d’abord un planning.');let p=+$('#people').value||4,m={};plan.forEach(r=>r.ingredients.forEach(([n,q,u])=>{let k=norm(n)+'|'+u;if(!m[k])m[k]={n,q:0,u,checked:false};m[k].q+=q*p/r.servings}));shop=Object.values(m).sort((a,b)=>a.n.localeCompare(b.n));localStorage.setItem('hgshop',JSON.stringify(shop));renderShop();view('shopping')};
function renderShop(){$('#shoppingList').innerHTML=`<div class="shop">${shop.map((x,i)=>`<label class="${x.checked?'checked':''}"><input type="checkbox" data-c="${i}" ${x.checked?'checked':''}><span>${x.n} — ${Math.round(x.q*10)/10} ${x.u}</span></label>`).join('')}</div>`;$$('[data-c]').forEach(c=>c.onchange=()=>{shop[+c.dataset.c].checked=c.checked;localStorage.setItem('hgshop',JSON.stringify(shop));renderShop()})}$('#uncheck').onclick=()=>{shop.forEach(x=>x.checked=false);renderShop()};$('#surprise').onclick=()=>$('#surpriseCard').innerHTML=card(R[Math.floor(Math.random()*R.length)]);
fetch('recipes.json').then(r=>r.json()).then(x=>{R=x;[...new Set(R.map(r=>r.category))].sort().forEach(c=>$('#cat').insertAdjacentHTML('beforeend',`<option>${c}</option>`));renderRecipes();try{let s=JSON.parse(localStorage.getItem('hgplan'));if(s){$('#people').value=s.p;plan=s.ids.map(id=>R.find(r=>r.id===id)).filter(Boolean);renderPlan()}shop=JSON.parse(localStorage.getItem('hgshop'))||[];renderShop()}catch(e){};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')});
