let recipes=[],plan=[],shopping=[];
const days=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"], slots=["Midi","Soir"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=s=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const saveRecipes=()=>localStorage.setItem("hg-recipes-v25",JSON.stringify(recipes));
const customRecipes=()=>JSON.parse(localStorage.getItem("hg-recipes-v25")||"null");
async function init(){renderDayChoices();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");const stored=customRecipes();if(stored)recipes=stored;else{const r=await fetch(`recipes.json?_=${Date.now()}`,{cache:"no-store"});recipes=await r.json()}fillCategories();renderRecipes();loadSaved();}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
$$('nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
function fillCategories(){const old=$('#category').value;$('#category').innerHTML='<option value="">Toutes catégories</option>'+[...new Set(recipes.map(r=>r.category).filter(Boolean))].sort().map(c=>`<option>${esc(c)}</option>`).join('');$('#category').value=old}
function recipeCard(r){return `<article class="recipe"><button class="recipe-head" data-open="${esc(r.id)}"><div class="meta">${esc(r.category)} · ${r.time} min · ${r.servings} pers. · ${esc(r.temperature)}</div><h3>${esc(r.title)}</h3><div class="badges">${(r.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div></button><div class="details"><h4>Ingrédients</h4><ul>${r.ingredients.map(i=>`<li>${esc(i[0])} : ${esc(i[1])} ${esc(i[2])}</li>`).join('')}</ul><h4>Préparation</h4><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><button class="edit" data-edit="${esc(r.id)}">Modifier</button></div></article>`}
function bindRecipeCards(root=document){root.querySelectorAll('.recipe-head').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('open'));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.edit))}
function renderRecipes(){const q=norm($('#search').value),cat=$('#category').value,max=+$('#maxTime').value||999;const found=recipes.filter(r=>(!cat||r.category===cat)&&r.time<=max&&(!q||norm(JSON.stringify(r)).includes(q)));$('#recipeList').innerHTML=found.map(recipeCard).join('')||'<p>Aucune recette trouvée.</p>';bindRecipeCards($('#recipeList'))}
$('#search').oninput=renderRecipes;$('#category').onchange=renderRecipes;$('#maxTime').onchange=renderRecipes;
$('#surpriseBtn').onclick=()=>{if(!recipes.length)return;$('#surpriseCard').innerHTML=recipeCard(recipes[Math.floor(Math.random()*recipes.length)]);bindRecipeCards($('#surpriseCard'))};
function slug(s){return norm(s).replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString(36)}
function openRecipe(id){const r=recipes.find(x=>x.id===id);$('#recipeDialogTitle').textContent=r?'Modifier la recette':'Nouvelle recette';$('#recipeId').value=r?.id||'';$('#recipeTitle').value=r?.title||'';$('#recipeCategory').value=r?.category||'';$('#recipeTime').value=r?.time||30;$('#recipeServings').value=r?.servings||4;$('#recipeTemperature').value=r?.temperature||'chaud';$('#recipeMeat').checked=!!r?.avecViande;$('#recipeIngredients').value=(r?.ingredients||[]).map(i=>i.join(' | ')).join('\n');$('#recipeSteps').value=(r?.steps||[]).join('\n');$('#recipeTags').value=(r?.tags||[]).join(', ');$('#deleteRecipe').classList.toggle('hidden',!r);$('#duplicateRecipe').classList.toggle('hidden',!r);$('#recipeDialog').showModal()}
$('#newRecipe').onclick=()=>openRecipe();$('#closeRecipe').onclick=()=>$('#recipeDialog').close();
function formRecipe(newId=false){const ingredients=$('#recipeIngredients').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [n,q='',u='']=line.split('|').map(x=>x.trim());const number=Number(String(q).replace(',','.'));return[n,Number.isFinite(number)&&q!==''?number:q,u]});return{id:newId||$('#recipeId').value||slug($('#recipeTitle').value),title:$('#recipeTitle').value.trim(),category:$('#recipeCategory').value.trim(),time:+$('#recipeTime').value,servings:+$('#recipeServings').value,temperature:$('#recipeTemperature').value,avecViande:$('#recipeMeat').checked,ingredients,steps:$('#recipeSteps').value.split('\n').map(x=>x.trim()).filter(Boolean),tags:$('#recipeTags').value.split(',').map(x=>x.trim()).filter(Boolean)}}
$('#recipeForm').onsubmit=e=>{e.preventDefault();const r=formRecipe();const i=recipes.findIndex(x=>x.id===r.id);if(i>=0)recipes[i]=r;else recipes.unshift(r);saveRecipes();fillCategories();renderRecipes();$('#recipeDialog').close()};
$('#deleteRecipe').onclick=()=>{const id=$('#recipeId').value;if(id&&confirm('Supprimer définitivement cette recette ?')){recipes=recipes.filter(r=>r.id!==id);saveRecipes();fillCategories();renderRecipes();$('#recipeDialog').close()}};
$('#duplicateRecipe').onclick=()=>{const r=formRecipe(slug($('#recipeTitle').value));r.title+=' (copie)';recipes.unshift(r);saveRecipes();fillCategories();renderRecipes();$('#recipeDialog').close()};
function renderDayChoices(){const stored=JSON.parse(localStorage.getItem('hg-selected-days')||'[0,1,2,3,4,5,6]');$('#dayChoices').innerHTML=days.map((d,i)=>`<label class="day-choice ${stored.includes(i)?'selected':''}"><input type="checkbox" data-day="${i}" ${stored.includes(i)?'checked':''}><span>${d}</span></label>`).join('');$$('[data-day]').forEach(c=>c.onchange=()=>{c.parentElement.classList.toggle('selected',c.checked);localStorage.setItem('hg-selected-days',JSON.stringify(selectedDays()));updateDayStatus()});updateDayStatus()}
function selectedDays(){return $$('[data-day]:checked').map(x=>+x.dataset.day)}function updateDayStatus(){const n=selectedDays().length;$('#selectedDaysStatus').textContent=`${n} jour${n>1?'s':''}`}
$('#selectAllDays').onclick=()=>{$$('[data-day]').forEach(x=>{x.checked=true;x.parentElement.classList.add('selected')});localStorage.setItem('hg-selected-days','[0,1,2,3,4,5,6]');updateDayStatus()};$('#clearAllDays').onclick=()=>{$$('[data-day]').forEach(x=>{x.checked=false;x.parentElement.classList.remove('selected')});localStorage.setItem('hg-selected-days','[]');updateDayStatus()};
function choices(exclude=[]){const max=+$('#planTime').value||999;let pool=recipes.filter(r=>r.time<=max&&!exclude.includes(r.id));if(!pool.length)pool=recipes.filter(r=>!exclude.includes(r.id));return pool}
$('#generatePlan').onclick=()=>{const ds=selectedDays();if(!ds.length)return alert('Choisis au moins un jour.');plan=[];const used=[];ds.forEach(dayIndex=>slots.forEach(slot=>{let pool=choices(used);if(!pool.length){used.length=0;pool=choices()}const recipe=pool[Math.floor(Math.random()*pool.length)];if(recipe){plan.push({dayIndex,slot,recipe});used.push(recipe.id)}}));renderPlan()};
function scaled(r){const f=(+$('#people').value||4)/(r.servings||4);return r.ingredients.map(([n,q,u])=>`${n} : ${typeof q==='number'?Math.round(q*f*10)/10:q} ${u}`)}
function renderPlan(){if(!plan.length){$('#weekPlan').innerHTML='<p class="muted">Aucun repas planifié.</p>';return}$('#weekPlan').innerHTML=selectedDays().map(d=>{const meals=plan.filter(x=>x.dayIndex===d);return `<article class="day"><h3>${days[d]}</h3>${meals.map((m)=>{const idx=plan.indexOf(m),r=m.recipe;return `<div class="meal"><div><strong>${m.slot}</strong><div class="meta">${r.time} min</div><h4>${esc(r.title)}</h4></div><select data-plan="${idx}">${choices([]).map(x=>`<option value="${esc(x.id)}" ${x.id===r.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select><details><summary>Voir</summary><ul>${scaled(r).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details></div>`}).join('')}</article>`}).join('');$$('[data-plan]').forEach(s=>s.onchange=()=>{plan[+s.dataset.plan].recipe=recipes.find(r=>r.id===s.value);renderPlan()})}
$('#people').onchange=()=>{localStorage.setItem('hg-people',$('#people').value);renderPlan()};$('#clearPlan').onclick=()=>{if(confirm('Vider le planning ?')){plan=[];localStorage.removeItem('hg-plan-v25');renderPlan()}};
$('#savePlan').onclick=()=>{localStorage.setItem('hg-plan-v25',JSON.stringify({people:+$('#people').value,time:$('#planTime').value,items:plan.map(x=>({dayIndex:x.dayIndex,slot:x.slot,id:x.recipe.id}))}));alert('Planning enregistré.')};
$('#buildShopping').onclick=()=>{if(!plan.length)return alert('Génère d’abord un planning.');const map={};plan.forEach(x=>scaledRaw(x.recipe).forEach(([n,q,u])=>{const k=norm(n)+'|'+u;if(!map[k])map[k]={name:n,qty:0,unit:u,checked:false};if(typeof q==='number')map[k].qty+=q;else if(!map[k].text)map[k].text=q}));shopping=Object.values(map).sort((a,b)=>a.name.localeCompare(b.name));saveShopping();renderShopping();switchView('shopping')};
function scaledRaw(r){const f=(+$('#people').value||4)/(r.servings||4);return r.ingredients.map(([n,q,u])=>[n,typeof q==='number'?Math.round(q*f*10)/10:q,u])}function saveShopping(){localStorage.setItem('hg-shopping-v25',JSON.stringify(shopping))}
function renderShopping(){if(!shopping.length){$('#shoppingList').innerHTML='<p class="muted">La liste est vide.</p>';return}$('#shoppingList').innerHTML=`<div class="shop-group">${shopping.map((x,i)=>`<label class="shop-item ${x.checked?'checked':''}"><input type="checkbox" data-shop="${i}" ${x.checked?'checked':''}><span><strong>${esc(x.name)}</strong>${x.qty?` — ${Math.round(x.qty*10)/10} ${esc(x.unit)}`:x.text?` — ${esc(x.text)} ${esc(x.unit)}`:''}</span></label>`).join('')}</div>`;$$('[data-shop]').forEach(c=>c.onchange=()=>{shopping[+c.dataset.shop].checked=c.checked;saveShopping();renderShopping()})}
$('#addShopping').onclick=()=>{const name=prompt('Article à ajouter :');if(name?.trim()){shopping.push({name:name.trim(),qty:0,unit:'',checked:false});shopping.sort((a,b)=>a.name.localeCompare(b.name));saveShopping();renderShopping()}};$('#clearChecks').onclick=()=>{shopping.forEach(x=>x.checked=false);saveShopping();renderShopping()};$('#removeChecked').onclick=()=>{shopping=shopping.filter(x=>!x.checked);saveShopping();renderShopping()};$('#clearShopping').onclick=()=>{if(confirm('Vider toute la liste de courses ?')){shopping=[];saveShopping();renderShopping()}};
$('#printPlan').onclick=()=>print();$('#printShopping').onclick=()=>print();
function loadSaved(){const p=+localStorage.getItem('hg-people');if(p)$('#people').value=p;try{const s=JSON.parse(localStorage.getItem('hg-plan-v25'));if(s){$('#people').value=s.people||4;$('#planTime').value=s.time||'';plan=(s.items||[]).map(x=>({...x,recipe:recipes.find(r=>r.id===x.id)})).filter(x=>x.recipe);renderPlan()}shopping=JSON.parse(localStorage.getItem('hg-shopping-v25')||'[]');renderShopping()}catch(e){console.error(e)}}
let deferredPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
init().catch(e=>{console.error(e);$('#recipeList').innerHTML='<p>Impossible de charger les recettes.</p>'});
