/* Herbier Gourmand v2.9.7.16.4 — moteur photo commun */
(()=>{
'use strict';
const DB_NAME='hg-media-v1', STORE='photos', SHOP_PHOTO_MAP='hg-shopping-photo-map-v1';
let dbPromise=null, objectUrls=new Map(), pendingTarget=null;
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
async function putPhoto(rec){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(rec);t.oncomplete=()=>res(rec.id);t.onerror=()=>rej(t.error)})}
async function getPhoto(id){if(!id)return null;const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function deletePhoto(id){if(!id)return;const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function allPhotos(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function photoId(){return `photo-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
async function compress(file){const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});const max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bitmap,0,0,w,h);bitmap.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.84));if(!blob)throw new Error('Compression impossible');return {blob,width:w,height:h,mime:'image/jpeg'}}
function shopMap(){try{return JSON.parse(localStorage.getItem(SHOP_PHOTO_MAP)||'{}')}catch{return {}}}
function saveShopMap(m){localStorage.setItem(SHOP_PHOTO_MAP,JSON.stringify(m))}
function owner(kind,id){if(kind==='recipe')return recipes.find(x=>x.id===id);if(kind==='herb')return herbs.find(x=>x.id===id);if(kind==='produce')return produceItems.find(x=>x.id===id);if(kind==='shopping')return shopping.find(x=>x.id===id);return null}
function persist(kind,item){if(kind==='recipe'){saveRecipes();plan.forEach(p=>{if(p.recipe?.id===item.id)p.recipe=item});savePlanData()}else if(kind==='herb'){localStorage.setItem(herbStore,JSON.stringify(herbs))}else if(kind==='produce'){localStorage.setItem(produceStore,JSON.stringify(produceItems))}else if(kind==='shopping'){const m=shopMap();m[norm(item.name)]=item.photoId||'';saveShopMap(m);saveShopping()}registerProtectedChange();markDirty()}
async function assignFile(kind,id,file){const item=owner(kind,id);if(!item||!file)return;const old=item.photoId||'';const img=await compress(file),idp=photoId();await putPhoto({id:idp,blob:img.blob,mime:img.mime,width:img.width,height:img.height,createdAt:new Date().toISOString()});item.photoId=idp;persist(kind,item);if(old&&old!==idp)await deletePhoto(old);refresh(kind,id)}
async function remove(kind,id){const item=owner(kind,id);if(!item?.photoId)return;if(!confirm('Supprimer cette image ?'))return;const old=item.photoId;item.photoId='';persist(kind,item);await deletePhoto(old);refresh(kind,id)}
function refresh(kind,id){if(kind==='recipe'){renderRecipes();if(viewedRecipeId===id)showRecipe(id)}else if(kind==='herb'){renderHerbs();if(viewedHerbId===id)showHerb(id)}else if(kind==='produce'){renderProduce();if(viewedProduceId===id)showProduce(id)}else if(kind==='shopping'){renderShopping();if($('#shoppingDialog')?.open)openShopping(id)}setTimeout(hydrate,0)}
function slot(kind,id,pid,size='small',allowAdd=true){return `<div class="hg-photo-slot hg-photo-${size}" data-photo-wrap><button type="button" class="hg-photo-button ${pid?'has-photo':'empty'}" ${pid?`data-photo-open="${esc(pid)}"`:(allowAdd?`data-photo-add="${kind}|${esc(id)}"`:'disabled')} aria-label="${pid?'Afficher l’image':'Ajouter image'}">${pid?`<img data-photo-id="${esc(pid)}" alt="">`:'<span>Ajouter<br>image</span>'}</button>${pid&&size!=='small'?`<div class="hg-photo-actions"><button type="button" data-photo-add="${kind}|${esc(id)}">Remplacer</button><button type="button" data-photo-remove="${kind}|${esc(id)}">Supprimer</button></div>`:''}</div>`}
async function hydrate(root=document){const imgs=[...root.querySelectorAll('img[data-photo-id]')];for(const img of imgs){const id=img.dataset.photoId;if(img.dataset.loaded===id)continue;try{const rec=await getPhoto(id);if(!rec)continue;let url=objectUrls.get(id);if(!url){url=URL.createObjectURL(rec.blob);objectUrls.set(id,url)}img.src=url;img.dataset.loaded=id}catch(e){console.warn('Photo indisponible',e)}}bindPhotoControls(root)}
function bindPhotoControls(root=document){root.querySelectorAll('[data-photo-add]').forEach(b=>{if(b.dataset.photoBound)return;b.dataset.photoBound='1';b.onclick=e=>{e.stopPropagation();const [kind,id]=b.dataset.photoAdd.split('|');openChooser(kind,id)}});root.querySelectorAll('[data-photo-open]').forEach(b=>{if(b.dataset.photoBound)return;b.dataset.photoBound='1';b.onclick=e=>{e.stopPropagation();openFull(b.dataset.photoOpen)}});root.querySelectorAll('[data-photo-remove]').forEach(b=>{if(b.dataset.photoBound)return;b.dataset.photoBound='1';b.onclick=e=>{e.stopPropagation();const [kind,id]=b.dataset.photoRemove.split('|');remove(kind,id)}})}
function ensureUi(){if($('#hgPhotoChooser'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="hgPhotoChooser" class="hg-photo-dialog"><div class="dialog-head"><h2>Ajouter une image</h2><button type="button" data-photo-close>×</button></div><p>Choisis la source de l’image.</p><div class="hg-photo-choice"><button type="button" id="hgPhotoCamera" class="primary">Prendre une photo</button><button type="button" id="hgPhotoGallery">Choisir une image</button></div><input hidden id="hgPhotoCameraInput" type="file" accept="image/*" capture="environment"><input hidden id="hgPhotoGalleryInput" type="file" accept="image/*"></dialog><dialog id="hgPhotoFull" class="hg-photo-full"><button type="button" class="hg-photo-full-close">Fermer</button><img alt="Image Herbier Gourmand"></dialog>`);$('#hgPhotoChooser [data-photo-close]').onclick=()=>$('#hgPhotoChooser').close();$('#hgPhotoCamera').onclick=()=>$('#hgPhotoCameraInput').click();$('#hgPhotoGallery').onclick=()=>$('#hgPhotoGalleryInput').click();for(const id of ['hgPhotoCameraInput','hgPhotoGalleryInput'])$('#'+id).onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f||!pendingTarget)return;$('#hgPhotoChooser').close();try{await assignFile(pendingTarget.kind,pendingTarget.id,f)}catch(err){console.error(err);alert('Impossible d’ajouter cette image.')}};$('#hgPhotoFull .hg-photo-full-close').onclick=()=>$('#hgPhotoFull').close();$('#hgPhotoFull').onclick=e=>{if(e.target===$('#hgPhotoFull'))$('#hgPhotoFull').close()}}
function openChooser(kind,id){if(READONLY)return;ensureUi();pendingTarget={kind,id};$('#hgPhotoChooser').showModal()}
async function openFull(id){ensureUi();const rec=await getPhoto(id);if(!rec)return;let url=objectUrls.get(id);if(!url){url=URL.createObjectURL(rec.blob);objectUrls.set(id,url)}$('#hgPhotoFull img').src=url;$('#hgPhotoFull').showModal()}

// Recettes : vignette en liste, plus grande en détail.
const oldRecipeCard=recipeCard;recipeCard=function(r){return oldRecipeCard(r).replace('</article>',`${slot('recipe',r.id,r.photoId,'small',true)}</article>`)};
const oldShowRecipe=showRecipe;showRecipe=function(id,from=''){oldShowRecipe(id,from);const r=recipes.find(x=>x.id===id),head=$('#recipeViewContent .recipe-title');if(r&&head){head.insertAdjacentHTML('beforeend',slot('recipe',r.id,r.photoId,'detail',true));hydrate(head)}};
const oldShowPlanRecipe=showPlanRecipe;showPlanRecipe=function(index,opts={}){oldShowPlanRecipe(index,opts);const m=plan[index],head=$('#recipeViewContent .recipe-title');if(m&&head){head.insertAdjacentHTML('beforeend',slot('recipe',m.recipe.id,m.recipe.photoId,'detail',true));hydrate(head)}};

// Réhydrate les listes après chaque filtre/recherche/rendu.
const baseRenderRecipes=renderRecipes;renderRecipes=function(){baseRenderRecipes();setTimeout(()=>hydrate($('#recipeList')),0)};
const baseRenderHerbs=renderHerbs;renderHerbs=function(){baseRenderHerbs();setTimeout(()=>hydrate($('#herbList')),0)};
const baseRenderProduce=renderProduce;renderProduce=function(){baseRenderProduce();setTimeout(()=>hydrate($('#produceList')),0)};

// Plantes & épices et Fruits & légumes : même langage visuel que Recettes.
const oldHerbCard=herbCard;herbCard=function(h){return oldHerbCard(h).replace('</article>',`${slot('herb',h.id,h.photoId,'small',true)}</article>`)};
const oldShowHerb=showHerb;showHerb=function(id,from=''){oldShowHerb(id,from);const h=herbs.find(x=>x.id===id),head=$('#herbViewContent .herb-detail-head');if(h&&head){head.insertAdjacentHTML('beforeend',slot('herb',h.id,h.photoId,'detail',true));hydrate(head)}};
const oldProduceCard=produceCard;produceCard=function(p){return oldProduceCard(p).replace('</article>',`${slot('produce',p.id,p.photoId,'small',true)}</article>`)};
const oldShowProduce=showProduce;showProduce=function(id,from=''){oldShowProduce(id,from);const p=produceItems.find(x=>x.id===id),head=$('#produceViewContent .produce-detail-head');if(p&&head){head.insertAdjacentHTML('beforeend',slot('produce',p.id,p.photoId,'detail',true));hydrate(head)}};

// Courses : photo = coche ; sans photo, la coche actuelle reste.
const oldShoppingRow=shoppingRow;shoppingRow=function(x){if(!x.photoId){const m=shopMap(),pid=m[norm(x.name)];if(pid)x.photoId=pid}let html=oldShoppingRow(x);if(x.photoId)html=html.replace(/<input type="checkbox" data-shop-check="[^"]+"[^>]*>/,`<button type="button" class="hg-shop-photo-check ${x.checked?'checked':''}" data-shop-photo-check="${esc(x.id)}"><img data-photo-id="${esc(x.photoId)}" alt=""></button>`);return html};
const oldRenderShopping=renderShopping;renderShopping=function(){oldRenderShopping();$$('[data-shop-photo-check]').forEach(b=>b.onclick=()=>{const x=shopping.find(i=>i.id===b.dataset.shopPhotoCheck);if(x){x.checked=!x.checked;saveShopping();renderShopping()}});hydrate($('#shoppingList'))};
const oldOpenShopping=openShopping;openShopping=function(id=''){oldOpenShopping(id);const x=shopping.find(i=>i.id===id);if(!x)return;const form=$('#shoppingForm'),orig=$('#shoppingOrigins');form.querySelector('.hg-shopping-photo-panel')?.remove();orig.insertAdjacentHTML('beforebegin',`<div class="hg-shopping-photo-panel"><div><strong>Image de l’article</strong><p class="muted">Emballage, bouteille, bouquet ou présentation à reconnaître lors de l’achat.</p></div>${slot('shopping',x.id,x.photoId,'detail',true)}</div>`);hydrate(form)};

// Les photos Courses sont mémorisées par nom d'article pour les listes futures.
const oldNormalizeShoppingItem=normalizeShoppingItem;normalizeShoppingItem=function(x={}){const item=oldNormalizeShoppingItem(x),m=shopMap();item.photoId=x.photoId||m[norm(item.name)]||'';return item};

// Sauvegarde .hgbak : embarque les photos compressées avec les autres données.
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function dataURLToBlob(s){const r=await fetch(s);return r.blob()}
window.hgMediaExport=async()=>{const rows=await allPhotos();return Promise.all(rows.map(async r=>({...r,blob:await blobToDataURL(r.blob)})))};
window.hgMediaImport=async rows=>{if(!Array.isArray(rows))return;for(const r of rows){if(!r?.id||!r.blob)continue;await putPhoto({...r,blob:await dataURLToBlob(r.blob)})}};

ensureUi();renderRecipes();renderHerbs();renderProduce();renderShopping();hydrate();
})();
